OPCODE = ['blci', 'vcmpnge_uqss', 'cmpxchg8b', 'vpmovusqd', 'vcvtneoph2ps',
'fcmovna', 'vpaddsw', 'vfmaddsub213ph', 'incsspd', 'pmuldq', 'vbroadcastf64x2',
'vcmpunord_qss', 'vfmsub231ph', 'vpcmpgtw', 'imul', 'vpminsb', 'vmovmskps',
'vmsave', 'vpcomnequw', 'rdfsbase', 'vpmovsdb', 'vmaskmovdqu', 'pmovzxwd',
'vextractps', 'fldpi', 'fimul', 'vzeroall', 'vcmpeq_usph', 'vpshaw',
'cvtss2si', 'vpmovd2m', 'je', 'xsaveopt', 'vprotq', 'vgetexpss', 'ptest',
'vpclmullqhqdq', 'psllq', 'rmpquery', 'vcmpeq_ospd', 'wbnoinvd', 'hlt',
'vfnmadd213sd', 'vpcmpw', 'vpshrdw', 'vpcomd', 'lwpins', 'sgdt', 'vunpcklps',
'pavgw', 'minpd', 'setng', 'cmppd', 'fxsave64', 'vcmpngt_usph', 'sysenter',
'blsic', 'vptestnmb', 'vpabsw', 'pmuludq', 'vlddqu', 'vpmacssdd', 'cvtps2pd',
'vpcomequq', 'vcmptrue_uqph', 'ud1', 'vpmovdw', 'vpcmpleb', 'vprolvq',
'vpcmpnltud', 'vcmpneq_oqsh', 'psrldq', 'vcvtss2usi', 'vpsraw', 'pmaddwd',
'vpcomgtw', 'vpopcntd', 'psubb', 'vmulsh', 'vfmsub132pd', 'nop',
'fldz', 'roundss', 'vfmsubaddps', 'ftst', 'setbe', 'vpshab', 'vcvtdq2ph',
'vcmpgt_oqsh', 'vcmptrue_uqps', 'vpunpcklwd', 'vpclmulhqlqdq', 'rsqrtss',
'fisubr', 'xacquire', 'xrelease', 'wrmsr', 'repnz', 'vpdpwssds', 'insertps',
'axor', 'vscatterpf0dpd', 'vcmpneqss', 'vpermt2q', 'movzb', 'vcmplt_ossh',
'testui', 'vpcomtrued', 'vshufi64x2', 'vcmpge_oqph', 'vshuff64x2', 'setnae',
'skinit', 'aesdec128kl', 'maxpd', 'vfmsubaddpd', 'vcvtdq2pd', 'vcmpge_oqsh',
'vucomiss', 'vcvtsh2ss', 'wrmsrns', 'movntpd', 'vcvtsh2sd', 'fldl2t',
'knotb', 'rex.wrxb', 'wrussd', 'vpmovsqb', 'vcvtps2pd', 'cwtd',
'xrstors64', 'vrsqrt28pd', 'rmpadjust', 'stgi', 'mulx', 'vblendmps', 'pextrd',
'vcmpgt_oqps', 'cmpcxadd', 'fucomip', 'vldmxcsr', 'vcmpeq_usss', 'vphaddbd',
'bndcl', 'vcmpunordpd', 'vpmullw', 'vcmptrue_uqss', 'cvtsi2sd', 'vsqrtph',
'vcomish', 'cmovg', 'vpcomgtud', 'vmovss', 'minss', 'pmovzxwq', 'vmovd',
'vcmpnle_uqsd', 'vpshldvd', 'ljmp', 'vfmsubpd', 'vfmsubss', 'encls',
'cmpngexadd', 'bswap', 'psignb', 'shrd', 'pclmulqdq', 'pconfig', 'xsave',
'pcmpeqd', 'vunpcklpd', 'fxrstor64', 'vpcomgeud', 'vpexpandw', 'vmgexit',
'int', 'fildll', 'clflushopt', 'vcmpneq_oqsd', 'vcmptrue_ussh', 'vcmple_ospd',
'vcvtusi2ss', 'vgetexpsh', 'vpminuw', 'vsqrtps', 'aesdeclast', 'xchg', 'pxor',
'vcmpeq_ossd', 'lgdt', 'shr', 'vpexpandq', 'kxnord', 'fyl2xp1', 'vpmadcswd',
'pfcmpgt', 'vscalefss', 'vpcmpnequb', 'pavgb', 'encodekey128', 'phsubw',
'vcmpgtph', 'vp2intersectd', 'fistp', 'vpcomltub', 'ffree', 'setnbe', 'aadd',
'fdecstp', 'vcvtpd2udq', 'vdbpsadbw', 'vfpclassph', 'vcmptrue_usph',
'vcmpnlt_uqps', 'vcvtuw2ph', 'pmulhrsw', 'vfmadd213sh', 'vpshldvw', 'vaddss',
'fdivr', 'paddq', 'xsavec', 'ud2b', 'vbcstnesh2ps', 'crc32', 'vpord',
'aesenc128kl', 'bsr', 'pmovsxbq', 'vucomisd', 'cmpxchg16b', 'paddusw',
'vcvtph2dq', 'fcmovae', 'vbroadcastf32x8', 'vcvtudq2pd', 'fndisi', 'kord',
'vsubss', 'vcmpeq_osps', 'vcmpnge_uqpd', 'vcvtpd2udqy', 'vrcp14pd', 'ktestq',
'retf', 'tdpbuud', 'ficom', 'vpcomleuw', 'aand', 'pfadd', 'vcmpneq_ossh',
'vpcomuw', 'vrangess', 'vcvtneps2bf16', 'pcmpestri', 'pmaxsb', 'kunpckwd',
'pminsw', 'pavgusb', 'kaddq', 'vsubsh', 'vcmpfalsess', 'vgatherqps',
'vcmpunord_ssd', 'vdppd', 'fistpll', 'fsubp', 'vcvtuqq2ph', 'vcmpnless',
'vpshufhw', 'vfnmsub231ph', 'adword', 'setno', 'cvtdq2pd', 'vpcomltb',
'mcommit', 'rdrand', 'vpmaskmovq', 'sha256msg1', 'vcmpnle_usph',
'vcmpunord_qsd', 'blsi', 'vfmaddsubps', 'mulsd', 'cvttsd2si', 'invvpid',
'vcmpnle_uqss', 'vpermd', 'pmaxsd', 'wait', 'sarx', 'wbinvd', 'vpmaxsd',
'xcrypt-ecb', 'vfnmsub132ps', 'ktestb', 'vrsqrtsh', 'vfmsubadd231ph',
'vpdpwssd', 'vcmpnle_ussh', 'monitorx', 'lfs', 'btc', 'xcryptcbc',
'gf2p8mulb', 'vcmpneqsd', 'vcvtpd2dq', 'cmovnge', 'bndcu', 'adc', 'vcmpordss',
'vblendvpd', 'vcvtpd2dqx', 'aesenclast', 'vpcmpgtb', 'int3', 'vbroadcasti128',
'rex', 'movmskpd', 'bts', 'cvtss2sd', 'cmpaxadd', 'vcvtuqq2psy', 'setnb',
'vcvttps2dq', 'vcmpnlt_uqss', 'vcmpnlt_uqsd', 'vcvtudq2phy', 'vpunpckldq',
'cbw', 'vcmple_oqsd', 'pmullw', 'frstpm', 'psmash', 'vcmpgeph', 'idiv',
'vcmpleps', 'vcmpnlesh', 'vcmplt_oqsh', 'vpmovdb', 'vfpclasspsx',
'vcmpnge_uqph', 'test', 'vcvttsd2si', 'vpclmullqlqdq', 'ktestw', 'tdpbusd',
'rdmsr', 'vpmulhw', 'movss', 'movsl', 'tpause', 'vcmppd', 'vcmpfalse_oqps',
'vcmpge_ossh', 'pmovzxbq', 'monitor', 'aesdec', 'vpsubsb', 'vcmpltsh',
'vpcomtrueub', 'lgs', 'wrssq', 'cwde', 'vpmovwb', 'vpsubusw', 'vmovhlps',
'vblendvps', 'vfnmadd231ps', 'pinsrd', 'neg', 'vpermi2q', 'pblendvb',
'unpckhps', 'vpcomfalseb', 'pcmpistri', 'vpaddusw', 'enqcmds', 'sysexit',
'fxrstor', 'vpcomleb', 'movups', 'lsl', 'fcmovu', 'vcmpgt_oqsd', 'vblendps',
'vcvtneps2bf16x', 'vfixupimmps', 'daa', 'vcmpless', 'str', 'pslld', 'loopz',
'vextractf128', 'vcmpneq_oqss', 'phaddsw', 'senduipi', 'movsw', 'vpaddusb',
'vcvttss2usi', 'vfrczpd', 'vpcmpneqb', 'vcmpneq_osps', 'es', 'pmovsxbd',
'vcmpeq_uqps', 'vpalignr', 'vfpclasspdz', 'xend', 'valignd', 'cmpltps',
'vcvttss2si', 'vpcmpd', 'vmlaunch', 'seamcall', 'vpshrdvq', 'vtestpd',
'pfrsqrt', 'vmovdqa', 'vfnmadd231ss', 'vfpclasspdx', 'lfence', 'sidt',
'sqrtpd', 'vcmpeq_uspd', 'vcvtph2qq', 'tilezero', 'lcall', 'stmxcsr',
'cmpordps', 'vfmadd132sh', 'vpexpandb', 'rex.rx', 'fsqrt', 'vcvttph2uw',
'vmovq', 'vpmovzxbd', 'vsqrtpd', 'vcvtsi2ss', 'pcmpeqb', 'movddup', 'vcmplesh',
'xsetbv', 'vcvttph2uqq', 'vpermil2ps', 'vpmovm2w', 'vshuff32x4',
'vcmpneq_usps', 'vpcmpnltq', 'movq', 'vpcmpnlew', 'vcvtpd2ph', 'f2xm1',
'pcmpistrm', 'vmovdqu16', 'vpconflictq', 'ssto', 'cvtpi2pd', 'paddd',
'vcvttps2uqq', 'vcmptrue_uqsh', 'sha1rnds4', 'vextractf32x4', 'setnl',
'vreducesh', 'aesdecwide256kl', 'vcmpunord_sps', 'vcmpngepd', 'seta',
'cvtpd2dq', 'vmaskmovps', 'movdqu', 'vmovlps', 'xorpd', 'bound', 'vrsqrtps',
'vgf2p8affineqb', 'vfmsub213pd', 'vcmpord_qps', 'xcryptofb', 'vfnmsub132pd',
'vpsllvq', 'jmp', 'vgatherpf1dps', 'vfmaddps', 'psrld', 'vpcmpgtq', 'cvtdq2ps',
'vcmpnle_ussd', 'cmove', 'vorpd', 'vpextrq', 'vpcomeqd', 'bextr', 'pmaxud',
'vpinsrw', 'vcmpsh', 'vzeroupper', 'psubw', 'vpand', 'vxorps', 'cmovb',
'vfmadd231ph', 'movlhps', 'kmovq', 'vcmpeq_ussh', 'psrad', 'orpd',
'vfmsub213ph', 'vcvttpd2udqy', 'packssdw', 'vsubph', 'vgatherqpd', 'cmpzxadd',
'vpcomuq', 'vcmpnge_uqsh', 'rdgsbase', 'vcmptrue_usps', 'vpcmpneqd',
'vcmpneq_oqph', 'vcmpnlt_usph', 'vfmaddsub213pd', 'vpmadd52huq',
'vcmpnge_uspd', 'pextrw', 'vmovsh', 'vcmpngt_ussh', 'vinserti32x4', 'vmfunc',
'pdep', 'vfixupimmpd', 'pclmulhqlqdq', 'vpshufd', 'cmplepd', 'vptestnmd',
'punpckhqdq', 'vcvtph2uqq', 'cmovnbe', 'vpopcntw', 'vinsertf64x4',
'vpcmpestri', 'wrfsbase', 'vcvtsd2si', 'vpcmpub', 'vpdpbsuds', 'prefetchw',
'cmc', 'rex64z', 'vp2intersectq', 'vpconflictd', 'fcomi', 'vmovdqu', 'tdpbsud',
'pminsb', 'vmrun', 'xgetbv', 'cmpnltpd', 'vcmptrue_usss', 'vpternlogq',
'vfmsub231sd', 'cmovge', 'vpavgw', 'rsqrtps', 'vpsrlw', 'arpl', 'aas',
'vscatterdps', 'vcvtpd2uqq', 'vaddsubpd', 'vpcmpnleuq', 'vcmpeq_ossh',
'vcvtudq2phx', 'vcompresspd', 'vpcomgeb', 'vptestmd', 'vinserti32x8', 'jbe',
'vpcmpneqw', 'pmovsxwq', 'vcmpunord_spd', 'rmpupdate', 'vpcmpleq',
'vcmpnlt_usps', 'wrssd', 'vfmsub231pd', 'vcmpge_oqss', 'loop', 'vandps',
'vcmpnge_uqps', 'vfmsub132ps', 'vcmpgtss', 'valignq', 'fidivr', 'vpmovm2q',
'vscatterpf1qps', 'vpdpbusd', 'vpcmpnequd', 'vcmpnge_usps', 'vpermilps',
'vpcomleq', 'vcmpnle_uqsh', 'roundpd', 'jne', 'ud2', 'vcvtph2uw', 'vminps',
'vmovddup', 'pblendw', 'setl', 'rexxyz', 'loopnz', 'ss', 'vpcomw',
'vcmple_osph', 'verr', 'vpexpandd', 'cmovz', 'vandpd', 'vcvtuqq2psx',
'vcmpltps', 'cmps', 'extractps', 'vmaxsd', 'addpd', 'jnge', 'xcrypt-ctr',
'cmpunordss', 'pmulhw', 'jz', 'vcmpgt_ossd', 'vrcpps', 'vgatherpf0qpd',
'vcmpps', 'vpcmpnled', 'packuswb', 'blendvps', 'jcxz', 'pshufw', 'vcmptruesh',
'cmpnzxadd', 'vfmadd132ph', 'vroundpd', 'v4fmaddss', 'vrangepd', 'vphadddq',
'prefetchwt1', 'add', 'vcvtqq2phx', 'clr', 'vcmpge_oqpd', 'vdivsh',
'vcmpnlt_ussh', 'setge', 'vpunpckhwd', 'vmulps', 'vptestmq', 'fcomip',
'vpgatherdq', 'vfmsubadd132pd', 'movd', 'vpcmpleuq', 'pushf', 'fbld',
'subss', 'vcmpsd', 'maxsd', 'rdsspq', 'cmpbxadd', 'orps', 'psubsb',
'vcmpnlt_uqpd', 'vextracti64x2', 'vcvtph2ps', 'andnps', 'scas', 'vfpclasspd',
'vmovhpd', 'tdcall', 'pi2fd', 'vpcmpeqd', 'vrcpph', 'vfmaddpd', 'pinsrb',
'vfpclasspsz', 'clflush', 'vpblendmd', 'pmaxuw', 'mulps', 'rdmsrlist',
'fcmovb', 'cmpngxadd', 'vpmovsxdq', 'vrndscaleph', 'psubusb', 'vcvttpd2uqq',
'vcmpfalse_osss', 'vcmpgt_osph', 'vcmpeqps', 'movsldup', 'bndmov', 'vpblendmq',
'vpcomeqq', 'vcmpngtss', 'vpshuflw', 'fpatan', 'vbcstnebf162ps', 'cmpnless',
'vpmovw2m', 'cmpeqsd', 'vpmacswd', 'cmpnlesd', 'roundps', 'vcmpord_qsh',
'rex64', 'vgetexpph', 'rdpru', 'vpcmpleuw', 'cli', 'prefetcht2', 'kmovw',
'vexp2ps', 'vcvtps2ph', 'vbroadcasti32x2', 'vfmsub213sh', 'vpsubsw',
'vpcomgew', 'vcmpgesh', 'movntsd', 'invlpgb', 'vpmovusdw', 'vcmpunord_qpd',
'fisttp', 'cmpeqps', 'vpshufbitqmb', 'cmovp', 'vpandn', 'vcmpordsh',
'cmpnbexadd', 'vfmsubadd132ps', 'vcmpeq_oqph', 'cvttps2dq', 'fnstcw',
'vextracti32x4', 'vfnmsub132sh', 'fisttpll', 'vpavgb', 'vpmovuswb', 'popcnt',
'vpcmpnltb', 'ud2a', 'vfmadd231ss', 'prefetcht1', 'vphsubd', 'lds',
'vcmpneq_oqpd', 'vpsubd', 'movsxd', 'pminub', 'jna', 'vpcompressd',
'cmpaexadd', 'cvtpd2ps', 'ins', 'vfmsubadd213pd', 'vpcomgtd',
'vreduceph', 'vpcomled', 'lldt', 'cmpnltss', 'pcmpgtb', 'vcvtsd2ss', 'kandnw',
'vpcomgeub', 'aesenc256kl', 'stc', 'fdisi', 'vpcmpled', 'kortestw',
'vcvttpd2udq', 'vsubsd', 'vpcmpltud', 'v4fmaddps', 'vpcomfalseub', 'enter',
'rex64xyz', 'vcmpneqsh', 'vucomish', 'vfnmadd231ph', 'vfmaddcsh', 'vcmpordsd',
'vpunpcklqdq', 'pfpnacc', 'vcvtneobf162ps', 'vcvtqq2phz', 'cmovpe', 'vpmuludq',
'vfnmsub132ss', 'vcmpunord_sss', 'vcmpnleps', 'vpcomfalseud', 'pmulld',
'vrcp14sd', 'vcomisd', 'data16', 'setnge', 'pf2id', 'vpcmpud', 'vpmaxub',
'vcmpgesd', 'pminsd', 'rdsspd', 'kandw', 'vcmpltph', 'vpcomtruew',
'cmpnaexadd', 'vxorpd', 'vfmadd231sd', 'vpermb', 'maxss', 'jnl', 'xsavec64',
'vmptrld', 'fnsetpm', 'psignw', 'vpshrdq', 'vfmsubsd', 'vminss', 'aesdec256kl',
'pfrsqit1', 'jnbe', 'std', 'vprold', 'setne', 'vcmpneq_uqph', 'vcvtps2dq',
'wrgsbase', 'vscatterqps', 'movabs', 'kshiftrw', 'fnstenv', 'vfnmaddss',
'vinsertf32x4', 'vfmadd132ps', 'cmovl', 'vcmplt_oqpd', 'vpshldd', 'repe',
'vprorq', 'vaddps', 'jo', 'vpcmpnequq', 'vcmpngeps', 'vcvttpd2dq',
'rex.b', 'loope', 'fmul', 'vcmplt_oqsd', 'fldl2e', 'fnclex', 'cmovno',
'vrsqrtph', 'andps', 'xrstor', 'vpblendmw', 'vfpclassphy',
'saveprevssp', 'vcvtpd2psx', 'vpsignd', 'vinserti64x2', 'jb', 'vcmpngeph',
'vmovntps', 'and', 'rcl', 'vpgatherqd', 'vpsubusb', 'vpcmpq', 'vgatherpf1qps',
'vpmovsxbw', 'vpblendd', 'vrangeps', 'vcmpgtsh', 'vcmpeq_oqpd',
'vcmpfalse_oqpd', 'vcmpord_qpd', 'vpcmpnleb', 'vphaddbq', 'vgetmantph',
'vcvtpd2phx', 'vpsrad', 'vptestnmw', 'vrcpsh', 'cdq', 'vpmovsxbd', 'minsd',
'vcmpngtsh', 'rex64xy', 'fsubrp', 'vmulsd', 'vpmovqb', 'lahf', 'vpaddw',
'punpcklbw', 'fist', 'vpdpbssd', 'femms', 'vcvtdq2ps', 'tdpbssd', 'rdtsc',
'bndldx', 'vcmpneq_uqsh', 'vcvtqq2phy', 'fclex', 'jrcxz', 'movapd', 'vpaddq',
'paddsb', 'vphaddubq', 'movdqa', 'cmpnlexadd', 'vpbroadcastmb2q', 'loopne',
'vpcompressb', 'vcmplt_osps', 'ja', 'knotd', 'cvttss2si', 'punpcklqdq',
'unpcklpd', 'invlpg', 'vcmpngt_uqpd', 'vfnmadd231sh', 'vpopcntb',
'vcmpeq_oqss', 'vpxorq', 'fxtract', 'vfmsub213ss', 'vpcomltd', 'rexxy',
'kortestq', 'vcmpgt_oqph', 'cmpltpd', 'llwpcb', 'or', 'feni', 'cmpnaxadd',
'vfmulcph', 'vroundsd', 'vpsadbw', 'dpps', 'vgetexpsd', 'movntps', 'vcmpeqsh',
'vmaxsh', 'cmpeqss', 'vcmpngt_ussd', 'vpshldq', 'xsha256', 'vcmpord_qph',
'vpackusdw', 'xcrypt-cfb', 'movzx', 'vpor', 'vcvttpd2dqy', 'vpmovzxdq',
'vpbroadcastb', 'addsd', 'smsw', 'vpackssdw', 'movshdup', 'phminposuw', 'shld',
'shl', 'phsubd', 'vpcomgtuq', 'sldt', 'vpsllw', 'movaps', 'vfmsub231sh',
'fsin', 'kxorq', 'vpcomtrueq', 'bnd', 'vshufi32x4', 'vandnps', 'xsaveopt64',
'ucomisd', 'vcmpngt_usss', 'vpcomfalseuq', 'vpsravq', 'vcmpngt_uqph', 'vprotd',
'cmpps', 'pmovsxdq', 'vaddpd', 'vcmpnle_usps', 'vfmaddsub231ps', 'rex.wrx',
'paddsw', 'xcrypt-cbc', 'vunpckhpd', 'vcvtsi2sh', 'tilestored', 'kxnorb',
'ficomp', 'kandq', 'vgatherdps', 'cmpnlxadd', 'fsub', 'vcmpgeps', 'endbr32',
'cmpnlepd', 'vcmpord_spd', 'pswapd', 'sha256rnds2', 'vcvtph2pd', 'kaddd',
'finit', 'vpblendw', 'setpe', 'aeskeygenassist', 'vpsignb', 'vcmpgtps',
'vmulph', 'vcmplt_ossd', 'vcmple_oqsh', 'vextracti32x8', 'vcmple_oqss',
'vmovntpd', 'vphaddubw', 'vcvtph2psx', 'vpshufb', 'setnc', 'pextrb',
'vfmsubadd213ps', 'vpcmpequq', 'vcvtuqq2pd', 'vfmsub132sd', 'vpmacssdqh',
'fldcw', 'fsubr', 'rsm', 'vcvtsi2sd', 'vpshlq', 'vpaddd', 'vpmovzxbq',
'vcmpnlt_uspd', 'pmaxub', 'vpmovsqw', 'vpermt2w', 'vfcmaddcsh', 'vcmpgt_osps',
'vmwrite', 'vpmovqd', 'vcmpeq_uqph', 'cmpxchg', 'psubsw', 'jc', 'vcmplesd',
'vsubpd', 'jpo', 'vaeskeygenassist', 'notrack', 'vpmovm2b', 'vpcmov',
'vp4dpwssds', 'vreducepd', 'kshiftrq', 'hnt', 'vpcomtrueuw', 'vpperm',
'vcmpnltss', 'cmpnltsd', 'fadd', 'vdpps', 'fucompi', 'vcvtuqq2phx', 'vpmaxsw',
'vcmple_osps', 'rstorssp', 'vmaxps', 'vpcomnequq', 'vcvtsh2si', 'pfsubr',
'fucomp', 'vcmpnlepd', 'vpmacsdd', 'vpandd', 'vfnmsub231ps', 'vpcomltuw',
'not', 'vfpclasspsy', 'vrcpss', 'cmpnbxadd', 'vcmpneq_uqps', 'vinsertf64x2',
'invpcid', 'setssbsy', 'cmovnb', 'vmclear', 'vcvttpd2dqx', 'pfsub',
'vinsertf128', 'vdivsd', 'korb', 'cmpnpxadd', 'vcmpngt_uqss', 'vpsraq',
'vpaddb', 'vpcomtrueud', 'rexy', 'fldt', 'vpextrw', 'seamops',
'vcmpfalse_osps', 'jnae', 'cvttpd2pi', 'vpextrb', 'kxnorq', 'vcmpeq_oqsd',
'vcvtsd2usi', 'cmovnl', 'vcmpge_osph', 'vpcomequw', 'vscatterdpd', 'cvtpd2pi',
'vpshrdvd', 'lar', 'vcmpngt_uqsh', 'divpd', 'vcvtsh2usi', 'pextrq',
'cvttpd2dq', 'vcmpfalse_ospd', 'vcmpord_qss', 'vrsqrt14ss', 'vinsertf32x8',
'vfmadd213ss', 'vhsubps', 'vpcomtrueb', 'vpmovqw', 'kxorw', 'aam',
'maskmovdqu', 'vcmpngtph', 'vsubps', 'vmovlpd', 'sal', 'addsubpd',
'vfpclasssh', 'vmovdqa64', 'kandd', 'vpsllvw', 'vmovaps', 'jnc', 'psllw',
'vcvtuqq2phy', 'xor', 'vreducesd', 'fstenv', 'vfnmaddsd', 'fdiv',
'vfmadd213pd', 'vcmpunordph', 'vprorvd', 'punpckhbw', 'vpdpbuud', 'vcvtusi2sh',
'vfcmaddcph', 'vpinsrq', 'vcmpord_qsd', 'vcmpunordps', 'vextractf64x2',
'clrssbsy', 'vfmadd213ph', 'vcvtps2phxx', 'fcmovnb', 'jpe', 'vpcomequd',
'vfmaddsub132ps', 'vpacksswb', 'jg', 'ffreep', 'cmpordsd', 'vpermi2pd',
'vfmadd213sd', 'rex.w', 'vcvttsh2si', 'vcmpfalse_ossh', 'umonitor',
'vfnmadd132ps', 'aad', 'vmovsd', 'lzcnt', 'vrcp28pd', 'pminuw', 'pmovsxbw',
'vsqrtsd', 'vpdpbuuds', 'vcmpnlt_uqsh', 'vbroadcastss', 'vfpclasssd', 'rcr',
'vpmovm2d', 'cmovnp', 'vpmulhuw', 'vpmaddubsw', 'vcmplt_osss', 'vpmovzxwd',
'vcmpgess', 'vandnpd', 'cvttps2pi', 'wrussq', 'fisub', 'vcmptrue_uqsd',
'vpmaxsq', 'phaddw', 'vpsrld', 'vpcomub', 'addr16', 'xcryptctr', 'cmovc',
'vpmovusqw', 'prefetchit1', 'vpdpbusds', 'vprord', 'js', 'vpbroadcastq',
'andn', 'mulpd', 'vgatherpf1qpd', 'movhps', 'setz', 'vpunpckhbw', 'ret',
'vfnmsub213ps', 'cdqe', 'vcvtss2sd', 'insertq', 'vcmpneq_uqsd', 'vpcmpeqb',
'int1', 'vpmovsdw', 'tlbsync', 'pfrcp', 'vpcmpequd', 'fstp', 'kaddw', 'fninit',
'vcmplt_oqss', 'vscatterqpd', 'vcvttps2udq', 'tilerelease', 'pcmpgtd',
'vcmple_ossd', 'vgatherpf0dpd', 'vpcomleub', 'repz', 'xsaves64', 'bsf',
'fmulp', 'rdseed', 'vblendmpd', 'vpmacsww', 'vfnmsub213sh', 'vhsubpd',
'rex.wx', 'vpcmpnleq', 'blsr', 'vpunpckhdq', 'sttilecfg', 'divss',
'vfpclassps', 'tzcnt', 'vpsubq', 'vcmpge_osss', 'bzhi', 'vbroadcastf64x4',
'vfmaddcph', 'vfnmadd132ph', 'blendpd', 'vcmpneq_osss', 'vpminsw', 'vcmpngtps',
'pfcmpge', 'vpcomequb', 'vcmpneqps', 'movupd', 'vgetmantsh', 'bt', 'punpcklwd',
'vcmpnlesd', 'vminsh', 'vcvtne2ps2bf16', 'shufpd', 'fxam', 'vphminposuw',
'vreduceps', 'vmovhps', 'movdir64b', 'movbe', 'verw', 'fchs', 'vfmadd132ss',
'cmppxadd', 'vpsrlvq', 'movhpd', 'vpscatterdq', 'vcvtps2phx', 'cmpsxadd',
'vfpclasspdy', 'vpmuldq', 'vminsd', 'vmovntdq', 'psraw', 'cwtl',
'vcmpnge_uqsd', 'vpcmpltw', 'jecxz', 'gf2p8affineinvqb', 'cmpnltps',
'vfmadd213ps', 'xsaves', 'vcmptrue_uqpd', 'fucompp', 'pand', 'vfcmulcsh',
'cmppoxadd', 'vpcmpestrm', 'vcmpunord_qsh', 'cmpbexadd', 'shufps', 'vpcomneqq',
'vshufpd', 'wrmsrlist', 'movntdqa', 'vmulss', 'vstmxcsr', 'scmp', 'vorps',
'vshufps', 'rdtscp', 'vextractf32x8', 'vpcmpuq', 'cmpeqpd', 'umwait',
'vmovapd', 'ldmxcsr', 'vscalefps', 'vaddph', 'vextracti64x4', 'movsd',
'vpcomltq', 'vcmpunordsh', 'pf2iw', 'sar', 'fucom', 'vcmpgt_osss',
'rex.r', 'vcmptrueps', 'pfrcpit1', 'vpcmpltuw', 'vpcmplew', 'faddp', 'sahf',
'comisd', 'xlat', 'blcs', 'sysret', 'vcmpge_ospd', 'vcmpeq_ussd', 'vphadduwd',
'cvtps2pi', 'vcvtpd2udqx', 'subps', 'rol', 'vfnmsubsd', 'vcvtpd2ps',
'vscalefpd', 'punpckldq', 'vcvtqq2ph', 'vprolq', 'vfnmsub231sd', 'vgf2p8mulb',
'vpcomltuq', 'vpcomgtq', 'vbroadcastf128', 'fcompp', 'vcmpfalsepd', 'rex.wb',
'vfnmsub213ph', 'vcmpnlt_ussd', 'pfcmpeq', 'vminph', 'xsusldtrk', 'movlpd',
'clts', 'vcmpnlt_uqph', 'slwpcb', 'inc', 'vpcmpistri',
'vcmpngt_usps', 'vpmacssww', 'in', 'vrndscalesd', 'kandnd', 'cmpunordps',
'vcmpfalse_osph', 'psubq', 'kandnb', 'setna', 'vrndscalepd', 'vprotb',
'vmovsldup', 'rcpps', 'vpcomleud', 'vfnmsub231sh', 'kaddb', 'sets',
'vcvtusi2sd', 'vreducess', 'vpmaxuq', 'vpmaddwd', 'vphaddbw', 'kandnq',
'cmovna', 'fiadd', 'clzero', 'pvalidate', 'vplzcntd', 'vpermi2w', 'vmovdqa32',
'pabsd', 'cmpexadd', 'cmovle', 'vbroadcasti32x8', 'vcmpeqsd', 'vpmaskmovd',
'vhaddpd', 'pfmul', 'vpermq', 'jns', 'vexp2pd', 'vfpclassphx', 'pext',
'incsspq', 'vdivph', 'cmpnsxadd', 'vfnmaddps', 'vpbroadcastmw2d',
'vfmsub213sd', 'rexxz', 'rex64x', 'vcmpeq_uqsd', 'vfnmsub132sd', 'pabsb',
'addsubps', 'blendvpd', 'vphaddwq', 'sha1msg1', 'stac', 'andpd', 'seto',
'fbstp', 'vcmpordps', 'vfnmadd213ss', 'vfixupimmss', 'xsha1', 'vcmpngesh',
'adcx', 'vcvtudq2ph', 'vcmpngtsd', 'fxch', 'vcmpord_sss', 'vpmadd52luq',
'vpmovusdb', 'shlx', 'vcvttsd2usi', 'vpxor', 'vfnmsubss', 'fabs', 'vpandnd',
'vcmpneq_oqps', 'vcmpltsd', 'ror', 'vptest', 'vcvttpd2qq', 'vcvtqq2pd',
'vpmacsdqh', 'fincstp', 'pcmpgtw', 'vpermi2b', 'vcvtph2udq', 'cmpgexadd',
'vcmpngt_uqps', 'vrndscaleps', 'cmpltsd', 'vpmovswb', 'vp4dpwssd', 'vprolvd',
'vptestmb', 'cqo', 'syscall', 'cmp', 't1mskc', 'vpcomgeuw', 'fstpt', 'vmload',
'adox', 'vpcmpnltw', 'fdivp', 'blsmsk', 'tdpfp16ps', 'vmmcall', 'vcvtqq2psx',
'vpbroadcastw', 'vcmpeq_usps', 'vpminub', 'kmovb', 'vcmpss', 'vcvtdq2phy',
'cmovs', 'vcmplt_oqph', 'vpmovmskb', 'leave', 'vmovlhps', 'vpcmpistrm',
'movmskps', 'vcmpgt_ospd', 'vpsrldq', 'vpmullq', 'vcmpeqph', 'movdiri',
'vbroadcasti64x4', 'vaesdeclast', 'vpackuswb', 'clgi', 'vcmpunordsd',
'setp', 'vcmpnle_uspd', 'vpsrlq', 'vcmpleph', 'vphaddwd', 'vmovdqu8',
'vcvtpd2phy', 'cld', 'vinserti128', 'vcmpordpd', 'vcvtss2si', 'vpsubb', 'dec',
'pop', 'vgetexpps', 'vpsrlvw', 'vpcmpequw', 'vbroadcastf32x2', 'rexz',
'cmpordpd', 'setns', 'vcmpnle_usss', 'movdq2q', 'cmpoxadd', 'getsec',
'fcmovne', 'phsubsw', 'vdivps', 'pfacc', 'vcmpnltsh', 'pcmpeqw', 'vcmpeqpd',
'vpermpd', 'vfnmsub213sd', 'vrcp14ps', 'vpshrdvw', 'vcmpfalse_oqph', 'jnz',
'kandb', 'vmresume', 'vpandnq', 'kshiftlb', 'vsqrtsh', 'vcmpnltsd', 'vcmpgtsd',
'vpcmpleud', 'cmpnoxadd', 'vcmpeqss', 'vcvtneps2bf16y', 'rexyz', 'vphaddd',
'fnop', 'vpcmpltuq', 'vphsubbw', 'kunpckbw', 'vminpd', 'vpmacssdql',
'xrstor64', 'vgf2p8affineinvqb', 'vpermw', 'vfnmsub213ss', 'dppd',
'vgetmantps', 'mulss', 'pinsrw', 'vcvtneeph2ps', 'vcmpnltps', 'rexx',
'kshiftlq', 'vhaddps', 'vpcomleuq', 'unpckhpd', 'pslldq', 'blcmsk', 'vpcomeqb',
'pcmpeqq', 'vcvtpd2phz', 'vpdpbsud', 'vcmpneq_uqpd', 'vphaddw', 'vpunpcklbw',
'vaesimc', 'vpmovsxwq', 'vscatterpf0dps', 'stui', 'pinsrq', 'vcvtps2uqq',
'vfmsub231ss', 'cmpunordpd', 'cmplesd', 'vpcomeqw', 'rex64y', 'vpmaxsb',
'serialize', 'prefetcht0', 'aesencwide128kl', 'vpblendmb', 'lmsw', 'popa',
'sti', 'sha1nexte', 'cbtw', 'psubusw', 'vrndscalesh', 'movsb', 'vcmplt_oqps',
'pmulhrw', 'vpcomltud', 'sqrtss', 'vcmpnle_uqpd', 'fld1', 'vfpclassphz', 'jge',
'vcvtqq2ps', 'vpabsq', 'vfnmadd132sd', 'fidiv', 'sha1msg2', 'vfmaddsd',
'vpxord', 'cmpneqpd', 'pmovzxbd', 'vscatterpf1dps', 'vpscatterdd', 'pfrcpit2',
'movhlps', 'vcmpfalsesh', 'movsx', 'kxord', 'kshiftrd', 'vpextrd', 'call',
'vmovdqu32', 'vcmpneq_ussd', 'pmaxsw', 'subsd', 'vfmsub132sh', 'vcmpneq_ossd',
'vpcompressq', 'vbroadcasti64x2', 'setnz', 'vbroadcastf32x4', 'vpcmpnltd',
'vpsravw', 'vmread', 'vcmpneq_ussh', 'vpslldq', 'vcvtpd2dqy', 'setnp',
'vpermps', 'vpgatherdd', 'pmovzxbw', 'vfnmadd231sd', 'vpshrdd', 'xtest',
'vpermi2ps', 'vcvtps2phxy', 'vrsqrt14sd', 'vpmaxuw', 'vfmsub231ps', 'fnsave',
'lret', 'sbb', 'vphsubwd', 'pminud', 'vexpandpd', 'jle', 'vpsubw', 'tzmsk',
'vcmpunord_qps', 'bndstx', 'vcvtneebf162ps', 'prefetchit0', 'vmovshdup',
'vmaxss', 'fcmovnu', 'psubd', 'addps', 'vpgatherqq', 'vpcomged', 'vpermilpd',
'rex64yz', 'vcmpngess', 'psrlq', 'vplzcntq', 'lss', 'vblendpd', 'vmaxph',
'divsd', 'vpcmpnltuq', 'jp', 'fxsave', 'fcmovbe', 'vcmpeq_uqpd', 'vgetexppd',
'fcomp', 'vmovdqu64', 'cltd', 'mov', 'haddpd', 'vcmpneq_uspd', 'cmpunordsd',
'vfmaddsub132pd', 'blcfill', 'vscatterpf0qpd', 'cmovnz', 'das', 'vpsllvd',
'invd', 'ssca', 'vfmsubps', 'vfnmadd213ps', 'vpmulhrsw', 'out',
'cmplexadd', 'vcmpneq_ospd', 'vprorvq', 'vfmsubadd213ph', 'fcom', 'extrq',
'gf2p8affineqb', 'punpckhdq', 'xadd', 'vcvtpd2qq', 'vpcmpnleuw', 'vcvttps2qq',
'vpsignw', 'shrx', 'aword', 'vcmpneq_usph', 'vfmaddsubpd', 'cwd',
'vfmaddsub213ps', 'vfmsub213ps', 'vpcomgtb', 'vbroadcastsd', 'vexpandps',
'vfnmadd213ph', 'addss', 'vscalefsd', 'xrstors', 'pmovmskb', 'pfnacc',
'vcvtps2udq', 'vpcmpnequw', 'vfnmsub213pd', 'vpinsrb', 'vcmplt_osph',
'vpblendvb', 'into', 'cmovpo', 'vaddsubps', 'vpermi2d', 'vcmpgt_oqss',
'endbr64', 'maxps', 'sqrtps', 'pmovzxdq', 'vpcomltw', 'mwaitx', 'vcmpngtpd',
'vcmpgtpd', 'vcvtps2qq', 'pcmpgtq', 'vrsqrt28sd', 'rex.x', 'vpscatterqd',
'vgatherpf1dpd', 'vcmple_osss', 'maskmovq', 'vpmovzxwq', 'vfmadd231pd',
'cmpnleps', 'blsfill', 'frndint', 'vfrczss', 'mwait', 'cmovng', 'vpcmpuw',
'vpcmpequb', 'vpcomgtub', 'vfmsub132ss', 'pmaddubsw', 'vrsqrt28ss',
'aesencwide256kl', 'vcmpeq_uqsh', 'xorps', 'vextracti128', 'vpcomneqw',
'vscalefph', 'fcmovnae', 'vpshlb', 'cmplxadd', 'divps', 'blendps', 'vptestmw',
'vcmpeq_oqsh', 'vpcompressw', 'jl', 'cmovae', 'vunpckhps', 'vrcp14ss',
'vcvtuqq2ps', 'vfpclassss', 'movntdq', 'fwait', 'vpbroadcastd', 'vfmaddss',
'vpshad', 'vpmovq2m', 'vpmovb2m', 'psignd', 'vpmaxud', 'fscale', 'vmovw',
'sete', 'pmulhuw', 'vphsubdq', 'cmpss', 'vpcomneqb', 'vfmaddsub132ph',
'vpminuq', 'hsubps', 'punpckhwd', 'vpshld', 'vfcmulcph', 'setpo',
'vcmple_oqpd', 'fneni', 'cmpnexadd', 'vpshaq', 'pshuflw', 'cmovo', 'psadbw',
'rdpid', 'vfmaddsub231pd', 'rex.rb', 'vcmpneq_osph', 'movntss', 'ud0',
'vmxoff', 'jno', 'vmaxpd', 'vpcomneqd', 'vpcmpnleud', 'enclu', 'setg', 'fstsw',
'cvtpi2ps', 'vcmpeq_osss', 'vrsqrt28ps', 'vaddsh', 'ldtilecfg', 'uiret',
'xstore', 'stos', 'vfmsub132ph', 'vcmpltpd', 'vcmptrueph', 'vfnmsub231pd',
'vpcomnequb', 'vpcomfalsed', 'vcvtdq2phx', 'rex.xb', 'vcmpnltpd', 'vpternlogd',
'vcmpge_oqsd', 'rex.rxb', 'vfnmsubps', 'pabsw', 'vextractf64x4', 'sha256msg2',
'push', 'vgetmantsd', 'vcmpord_sph', 'clac', 'cmpgxadd', 'fcmova', 'setnle',
'vmptrst', 'cmpleps', 'vpmovsxbq', 'vcmple_oqps', 'vaesenc', 'vroundss',
'vfmaddsub231ph', 'haddps', 'rdpmc', 'aesdecwide128kl', 'lidt', 'vpcomlew',
'vperm2i128', 'vpcmpltd', 'vpcmpb', 'vgetmantss', 'pshufd', 'vpcomgtuw',
'vcvtqq2psy', 'vpmovzxbw', 'enqcmd', 'data32', 'xabort',
'vcmpunord_sph', 'vcmpfalse_oqss', 'vpcmpnltub', 'pi2fw', 'vcmpnlt_usss',
'vcmpgepd', 'swapgs', 'vscatterpf0qps', 'vmovmskpd', 'mpsadbw', 'vpcomb',
'ucomiss', 'vcmpord_ssd', 'vcmpneq_uqss', 'vcmpfalseps', 'lods', 'packusdw',
'tileloaddt1', 'vpcmpeqq', 'vpinsrd', 'vcmpngt_uqsd', 'vgatherdpd', 'rorx',
'ktestd', 'vpunpckhqdq', 'fsave', 'cpuid', 'jnle', 'rex.wr', 'vaesdec',
'wrpkru', 'vcmplt_ospd', 'cldemote', 'cmppexadd', 'vpcomnequd', 'slod',
'rex.wxb', 'vcvtph2w', 'vpandq', 'fucomi', 'xsave64', 'emms', 'btr',
'vfmsubadd132ph', 'vfnmadd231pd', 'unpcklps', 'cmpneqps', 'bndcn', 'cmpneqss',
'vcmpunord_ssh', 'vfnmsubpd', 'fyl2x', 'vfnmadd132pd', 'vphaddubd', 'cvtsd2ss',
'vprotw', 'vtestps', 'vcompressps', 'vpcomtrueuq', 'vpmovusqb', 'vdpbf16ps',
'vcmpfalse_oqsh', 'fldln2', 'vpcmpleub', 'vfmadd132sd', 'vfnmsub132ph',
'vrangesd', 'vpmacsdql', 'vpabsb', 'vaesenclast', 'kshiftrb', 'cmpsd',
'cmpltss', 'vfixupimmsd', 'vpermil2pd', 'vpcmpneqq', 'vcvtw2ph', 'repne',
'paddb', 'kortestb', 'palignr', 'clui', 'vfmadd231sh', 'vpsravd', 'vpermt2b',
'vcvttph2dq', 'vcmptrue_ussd', 'vcmple_ossh', 'pshufhw', 'pusha', 'vpclmulqdq',
'fnstsw', 'vcmpunordss', 'vpcmpeqw', 'outs', 'jnp', 'vcmpfalse_ossd',
'vpcomfalseq', 'vpshldvq', 'vcmpeq_osph', 'vptestnmq', 'xstore-rng',
'vpmultishiftqb', 'vmovntdqa', 'encodekey256', 'vpermt2ps', 'cmovbe',
'ptwrite', 'vpminsd', 'vinserti64x4', 'rdpkru', 'iret', 'vcmpngesd', 'lock',
'movnti', 'invlpga', 'vpcomgeq', 'vpshlw', 'subpd', 'cmpncxadd',
'vfmsubadd231pd', 'fsincos', 'vfrczps', 'vpcomq', 'vfnmsub231ss', 'pfmax',
'invept', 'prefetch', 'vpcmpnltuw', 'vcmptruess', 'setae', 'vcmpneq_usss',
'blcic', 'tileloadd', 'pause', 'vphaddsw', 'vphsubsw', 'tdpbf16ps',
'vpscatterqq', 'vcvtudq2ps', 'vcvttph2qq', 'kortestd', 'jnb', 'fstcw',
'mfence', 'vfmadd132pd', 'ltr', 'cmovnc', 'vphadduwq', 'vcmpgt_ossh',
'vcvtss2sh', 'kxorb', 'vmxon', 'xcryptecb', 'korw', 'hsubpd', 'vaddsd',
'cmpordss', 'smov', 'addr32', 'prefetchnta', 'pfmin', 'kmovd', 'vgetmantpd',
'vcmpgt_oqpd', 'hreset', 'vpermt2pd', 'xresldtrk', 'fld', 'montmul',
'vmaskmovpd', 'vcmpnle_uqps', 'vcmpngt_uspd', 'enclv', 'vpminud', 'por',
'kshiftlw', 'psrlw', 'fcmovnbe', 'vcvttph2w', 'vmpsadbw', 'vcvttpd2udqx',
'fldlg2', 'vcmpnge_ussd', 'vpmulld', 'rex64xz', 'roundsd', 'popf', 'fild',
'bndmk', 'vpcmpltub', 'vcmpord_ssh', 'fcmove', 'v4fnmaddps', 'pclmullqlqdq',
'vcomiss', 'vcmpnge_usph', 'cmova', 'sqrtsd', 'vpcmpltq', 'fst', 'vcmpph',
'vphaddudq', 'vpcomud', 'vcvtuqq2phz', 'cmovne', 'vrcp28ps', 'les', 'vmcall',
'vpsllq', 'vmovups', 'vpdpbssds', 'kshiftld', 'andnpd', 'vdivpd', 'paddw',
'vpsrlvd', 'vpshldw', 'vfmulcsh', 'vpslld', 'vcvtsd2sh', 'vcmptruepd',
'vpcmpgtd', 'vcmpnleph', 'vpmovsqd', 'lea', 'sub', 'fcos', 'fsetpm', 'cmovnae',
'fprem1', 'vcmpfalseph', 'fptan', 'vpabsd', 'vscatterpf1qpd', 'rep',
'vpmovsxwd', 'vbroadcasti32x4', 'pclmullqhqdq', 'vcmpnle_uqph', 'vfnmadd213sh',
'vcmpeq_oqps', 'fdivrp', 'ht', 'vpmadcsswd', 'vperm2f128', 'aesimc', 'pshufb',
'vpcmpnleub', 'vscatterpf1dpd', 'fprem', 'kxnorw', 'vmovupd', 'minps',
'vpclmulhqhqdq', 'vcmpord_sps', 'vrcp28ss', 'cmovns', 'setb', 'vroundps',
'vcmpfalsesd', 'lwpval', 'jae', 'vrndscaless', 'pandn', 'xstorerng',
'vfmadd231ps', 'vfnmadd132ss', 'aaa', 'xcryptcfb', 'cltq', 'kunpckdq',
'comiss', 'vpminsq', 'clwb', 'cmovnle', 'vfrczsd', 'vrsqrt14ps', 'aor',
'vcmpordph', 'vpcmpltb', 'vcvttph2udq', 'div', 'cvtsi2ss', 'knotw', 'cvtsd2si',
'vfmsubadd231ps', 'vfnmadd213pd', 'vcmpnge_ussh', 'vpcomgeuq', 'vcmpneqph',
'vcmpneqpd', 'vcmptrue_uspd', 'vscalefsh', 'vgatherpf0dps', 'paddusb',
'sfence', 'xcrypt-ofb', 'cmpless', 'fldenv', 'rcpss', 'aesenc', 'vsqrtss',
'cmpneqsd', 'cvtps2dq', 'vpaddsb', 'setle', 'knotq', 'lddqu', 'vcmptruesd',
'korq', 'mul', 'vrcp28sd', 'vcmpge_osps', 'movs', 'vcmpfalse_oqsd',
'vcmpnltph', 'vcmpeq_uqss', 'vcmpge_oqps', 'setc', 'vpcomfalseuw',
'vfnmadd132sh', 'pcmpestrm', 'vdivss', 'seamret', 'vcmpnge_usss',
'vpcomfalsew', 'clc', 'vcmpunord_qph', 'v4fnmaddss', 'vinsertps', 'vfnmaddpd',
'vpopcntq', 'rex.wrb', 'vrsqrt14pd', 'vcmpltss', 'movzw', 'movlps', 'movntq',
'loadiwkey', 'vphsubw', 'vrsqrtss', 'fcompi', 'packsswb', 'phaddd', 'xbegin',
'pclmulhqhqdq', 'vcmpge_ossd', 'cqto', 'jng', 'vpmacsswd', 'pmovsxwd',
'vpermt2d', 'vcvtpd2psy', 'vcmple_oqph', 'movq2dq', 'vgatherpf0qps', 'vporq',
'frstor', 'vcmplepd', 'vmulpd', 'vcvttsh2usi']

REGISTERS = ['RAX', 'RBX', 'RCX', 'RDX', 'RSI', 'RDI', 'RBP', 'RSP', 'R8',
        'R9', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15',
        'EAX', 'EBX', 'ECX', 'EDX', 'ESI', 'EDI', 'EBP', 'ESP','R8D', 'R9D',
        'R10D', 'R11D', 'R12D', 'R13D', 'R14D', 'R15D',
        'AX', 'BX', 'CX', 'DX', 'BP', 'SI', 'DI', 'SP', 'R8W', 'R9W', 'R10W',
        'R11W', 'R12W', 'R13W', 'R14W', 'R15W',
        'AH', 'BH', 'CH', 'DH',
        'AL', 'BL', 'CL', 'DL', 'BPL', 'SIL', 'DIL', 'SPL', 'R8B', 'R9B',
        'R10B', 'R11B', 'R12B', 'R13B', 'R14B', 'R15B',
        'XMM0', 'XMM1', 'XMM2', 'XMM3', 'XMM4', 'XMM5', 'XMM6', 'XMM7', 'XMM8',
        'XMM9', 'XMM10', 'XMM11', 'XMM12', 'XMM13', 'XMM14', 'XMM15',
        'YMM0', 'YMM1', 'YMM2', 'YMM3', 'YMM4', 'YMM5', 'YMM6', 'YMM7', 'YMM8',
        'YMM9', 'YMM10', 'YMM11', 'YMM12', 'YMM13', 'YMM14', 'YMM15',
        'ZMM0', 'ZMM1', 'ZMM2', 'ZMM3', 'ZMM4', 'ZMM5', 'ZMM6', 'ZMM7', 'ZMM8',
        'ZMM9', 'ZMM10', 'ZMM11', 'ZMM12', 'ZMM13', 'ZMM14', 'ZMM15',
        'TMM0', 'TMM1', 'TMM2', 'TMM3', 'TMM4', 'TMM5', 'TMM6', 'TMM7', 'TMM8',
        'TMM9', 'TMM10', 'TMM11', 'TMM12', 'TMM13', 'TMM14', 'TMM15',
        'ST(0)', 'ST(1)', 'ST(2)', 'ST(3)', 'ST(4)', 'ST(5)', 'ST(6)', 'ST(7)', 'ST',
        'RIP',
        'CS', 'DS', 'ES', 'FS', 'GS', 'SS',
        'MM0', 'MM1', 'MM2', 'MM3', 'MM4', 'MM5', 'MM6', 'MM7'
]

PREFIX = [ 'addr32', 'adword', 'bnd', 'cs', 'data16', 'ds', 'fs', 'gs', 'hnt', 'ht', 'lock', 'notrack', 'rep', 'repe', 'repne', 'repnz', 'repz', 'rex', 'rex.b', 'rex.r', 'rex.rb', 'rex.rx', 'rex.rxb', 'rex.w', 'rex.wb', 'rex.wr', 'rex.wrb', 'rex.wrx', 'rex.wrxb', 'rex.wx', 'rex.wxb', 'rex.x', 'rex.xb', 'rex64', 'rex64x', 'rex64xy', 'rex64xyz', 'rex64xz', 'rex64y', 'rex64yz', 'rex64z', 'rexx', 'rexxy', 'rexxyz', 'rexxz', 'rexy', 'rexyz', 'rexz', 'wait', 'word', 'xacquire', 'xrelease']
PREFIX = [ 'addr32', 'adword', 'bnd', 'cs', 'data16', 'ds', 'hnt', 'ht', 'lock', 'notrack', 'rep', 'repe', 'rex', 'rex.w', 'wait', 'word', 'xacquire', 'xrelease']



candidates = ['AX', 'EAX', 'RAX', '[RAX]', 'XMM0', 'MMX0', 'YMM0', '1', '[1]']
candidates_att = ['%AX', '%EAX', '%RAX', '[%RAX]', '%XMM0', '%MMX0', '%YMM0', '$1', '[1]']
pseudo_prefix = ['{disp8}', '{disp32}', '{evex}', '{load}', '{store}', '{vex2}', '{vex3}']

REGISTERS = ['RAX', 'RBX', 'RCX', 'RDX', 'RSI', 'RDI', 'RBP', 'RSP', 'R8',
        'R9', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15',
        'EAX', 'EBX', 'ECX', 'EDX', 'ESI', 'EDI', 'EBP', 'ESP','R8D', 'R9D',
        'R10D', 'R11D', 'R12D', 'R13D', 'R14D', 'R15D',
        'AX', 'BX', 'CX', 'DX', 'BP', 'SI', 'DI', 'SP', 'R8W', 'R9W', 'R10W',
        'R11W', 'R12W', 'R13W', 'R14W', 'R15W',
        'AH', 'BH', 'CH', 'DH',
        'AL', 'BL', 'CL', 'DL', 'BPL', 'SIL', 'DIL', 'SPL', 'R8B', 'R9B',
        'R10B', 'R11B', 'R12B', 'R13B', 'R14B', 'R15B',
        'XMM0', 'XMM1', 'XMM2', 'XMM3', 'XMM4', 'XMM5', 'XMM6', 'XMM7', 'XMM8',
        'XMM9', 'XMM10', 'XMM11', 'XMM12', 'XMM13', 'XMM14', 'XMM15',
        'YMM0', 'YMM1', 'YMM2', 'YMM3', 'YMM4', 'YMM5', 'YMM6', 'YMM7', 'YMM8',
        'YMM9', 'YMM10', 'YMM11', 'YMM12', 'YMM13', 'YMM14', 'YMM15',
        'ZMM0', 'ZMM1', 'ZMM2', 'ZMM3', 'ZMM4', 'ZMM5', 'ZMM6', 'ZMM7', 'ZMM8',
        'ZMM9', 'ZMM10', 'ZMM11', 'ZMM12', 'ZMM13', 'ZMM14', 'ZMM15',
        'TMM0', 'TMM1', 'TMM2', 'TMM3', 'TMM4', 'TMM5', 'TMM6', 'TMM7', 'TMM8',
        'TMM9', 'TMM10', 'TMM11', 'TMM12', 'TMM13', 'TMM14', 'TMM15',
        'ST(0)', 'ST(1)', 'ST(2)', 'ST(3)', 'ST(4)', 'ST(5)', 'ST(6)', 'ST(7)', 'ST',
        'RIP',
        'CS', 'DS', 'ES', 'FS', 'GS', 'SS',
        'MM0', 'MM1', 'MM2', 'MM3', 'MM4', 'MM5', 'MM6', 'MM7'
]
# format {'expr' : (ArgType, ArgSize, mutation_list)}
TEMPLATE = {
    'REG8' : (1, 8, ['R11B'],
            ['AL', 'BL', 'CL', 'DL', 'BPL', 'SIL', 'DIL', 'SPL', 'R8B', 'R9B',
            'R10B', 'R11B', 'R12B', 'R13B', 'R14B', 'R15B']),
    'REG16' : (1, 16, ['R11W'],
            ['AX', 'BX', 'CX', 'DX', 'BP', 'SI', 'DI', 'SP', 'R8W', 'R9W', 'R10W',
            'R11W', 'R12W', 'R13W', 'R14W', 'R15W']),
    'REG32' : (1, 32, ['R11D'],
            ['EAX', 'EBX', 'ECX', 'EDX', 'ESI', 'EDI', 'EBP', 'ESP','R8D', 'R9D',
            'R10D', 'R11D', 'R12D', 'R13D', 'R14D', 'R15D']),
    'REG64' : (1, 64, ['R11'],
            ['RAX', 'RBX', 'RCX', 'RDX', 'RSI', 'RDI', 'RBP', 'RSP', 'R8',
            'R9', 'R10', 'R11', 'R12', 'R13', 'R14', 'R15']),
    'XMM' : (1, 128, ['XMM0'],
            ['XMM0']),
    'YMM' : (1, 256, ['YMM0'],
            ['YMM0']),
    'ZMM' : (1, 512, ['ZMM0'],
            ['ZMM0']),
    #'TMM' : (1, 1024, ['TMM0'],
    #         ['TMM0']),
    'X87': (1, 80, ['ST(1)'],
            ['ST(0)', 'ST(1)', 'ST(2)', 'ST(3)', 'ST(4)', 'ST(5)', 'ST(6)', 'ST(7)', 'ST']),
    'SEG' : (1, 16, ['CS'],
            ['CS', 'DS', 'ES', 'FS', 'GS', 'SS']),
    'MMX' : (1, 64, ['MM0'],
            ['MM0', 'MM1', 'MM2', 'MM3', 'MM4', 'MM5', 'MM6', 'MM7']),
    'MEMB' : (2, 0, ['[RAX]'],
            ['[RAX]']),
    'MEMBD' : (2, 0, ['[RAX+1]'], # mem_base
            ['[RAX+1]']),
    'MEMD' : (2, 0, ['[1]'],
            ['[1]']),
    'IMM' : (3, 0, ['1'],
            ['1'])
}


TEMPLATE_I386 = {
    'REG8' : (1, 8, ['AL'],
            ['AL', 'BL', 'CL', 'DL']),
    'REG16' : (1, 16, ['AX'],
            ['AX', 'BX', 'CX', 'DX', 'BP', 'SI', 'DI', 'SP']),
    'REG32' : (1, 32, ['EAX'],
            ['EAX', 'EBX', 'ECX', 'EDX', 'ESI', 'EDI', 'EBP', 'ESP']),
    'XMM' : (1, 128, ['XMM0'],
            ['XMM0']),
    'YMM' : (1, 256, ['YMM0'],
            ['YMM0']),
    'ZMM' : (1, 512, ['ZMM0'],
            ['ZMM0']),
    'X87': (1, 80, ['ST(1)'],
            ['ST(0)', 'ST(1)']),
    'SEG' : (1, 16, ['CS'],
            ['CS', 'DS', 'ES', 'FS', 'GS', 'SS']),
    'MMX' : (1, 64, ['MM0'],
            ['MM0', 'MM1', 'MM2', 'MM3', 'MM4', 'MM5', 'MM6', 'MM7']),
    'MEMB' : (2, 0, ['[EAX]'], # mem_base
            ['[EAX]']),
    'MEMBD' : (2, 0, ['[EAX+1]'], # mem_base_disp
            ['[EAX+1]']),
    'MEMD' : (2, 0, ['[1]'], # mem_disp
            ['[1]']),
    'IMM' : (3, 0, ['1'],
            ['1'])
}
