OPCODE = ['abs.d', 'abs.s', 'add.d', 'add', 'add.s', 'addi',
'addiu', 'addu', 'and', 'andi', 'bc1fl', 'bc1tl', 'beqzl', 'bgezall', 'bgezl',
'beql', 'bge', 'bgel', 'bgeu', 'bgeul', 'bgt', 'bgtl', 'bgtu', 'bgtul', 'ble',
'blel', 'bleu', 'bleul', 'bgtzl', 'blezl', 'blt', 'bltl', 'bltu', 'bltzall',
'bltzl', 'bnel', 'bnezl', 'break', 'c.eq.d', 'c.eq.s', 'c.f.d', 'c.f.s',
'c.le.d', 'c.le.s', 'c.lt.d', 'c.lt.s', 'c.nge.d', 'c.nge.s', 'c.ngl.d',
'c.ngl.s', 'c.ngle.d', 'c.ngle.s', 'c.ngt.d', 'c.ngt.s', 'c.ole.d', 'c.ole.s',
'c.olt.d', 'c.olt.s', 'c.seq.d', 'c.seq.s', 'c.sf.d', 'c.sf.s', 'c.ueq.d',
'c.ueq.s', 'c.ule.d', 'c.ule.s', 'c.ult.d', 'c.ult.s', 'c.un.d', 'c.un.s',
'c2', 'c3', 'ceil.w.d', 'ceil.w.s', 'cfc1', 'clo', 'clz', 'ctc1', 'cvt.d.s',
'cvt.d.w', 'cvt.l.d', 'cvt.l.s', 'cvt.s.d', 'cvt.s.w', 'cvt.w.d', 'cvt.w.s',
'deret', 'di', 'div', 'div.d', 'div.s', 'ehb', 'ei', 'eret', 'floor.w.d',
'floor.w.s', 'j', 'jal', 'jalr', 'jalr.hb', 'jalx', 'jr', 'jr.hb', 'lb', 'lbu',
'lh', 'lhu', 'li', 'lui', 'lw', 'lwc1', 'lwl', 'lwr', 'madd.d', 'madd',
'madd.s', 'maddu', 'mfc1', 'mfhc1', 'mfhi', 'mflo', 'mov.d', 'mov.s', 'move',
'movn.d', 'movn', 'movn.s', 'movz.d', 'movz', 'movz.s', 'msub.d', 'msub',
'msub.s', 'msubu', 'mtc1', 'mthc1', 'mthi', 'mtlo', 'mul.d', 'mul', 'mul.s',
'mult', 'multu', 'neg.d', 'neg', 'neg.s', 'negu', 'nmadd.d', 'nmadd.s',
'nmsub.d', 'nmsub.s', 'nop', 'nor', 'or', 'ori', 'pause', 'recip.d', 'recip.s',
'rfe', 'ror', 'round.w.d', 'round.w.s', 'rsqrt.d', 'rsqrt.s', 'sb', 'sdbbp',
'seb', 'seh', 'sh', 'sll', 'sllv', 'slt', 'slti', 'sltiu', 'sltu', 'sqrt.d',
'sqrt.s', 'sra', 'srav', 'srl', 'srlv', 'ssnop', 'sub.d', 'sub', 'sub.s',
'subu', 'sw', 'swc1', 'swl', 'swr', 'sync', 'syscall', 'teq', 'tge', 'tgeu',
'tlbp', 'tlbr', 'tlbwi', 'tlbwr', 'tlt', 'tltu', 'tne', 'trunc.w.d',
'trunc.w.s', 'wait', 'wsbh', 'xor', 'xori']

REGISTERS = [ '$3', '$4', '$5', '$6', '$7', '$8', '$9', '$10', '$11', '$12',
'$13', '$14', '$15', '$16', '$17', '$18', '$19', '$20', '$21', '$22', '$23',
'$24', '$25', '$26', '$27', '$28', '$29', '$30', '$31', '$v0', '$v1', '$a0',
'$a1', '$a2', '$a3', '$t0', '$t1', '$t2', '$t3', '$t4', '$t5', '$t6', '$t7',
'$s0', '$s1', '$s2', '$s3', '$s4', '$s5', '$s6', '$s7', '$t8', '$t9', '$f0',
'$f1', '$f2', '$f3', '$f4', '$f5', '$f6', '$f7', '$f8', '$f9', '$f10', '$f11',
'$f12', '$f13', '$f14', '$f15', '$f16', '$f17', '$f18', '$f19', '$f20', '$f21',
'$f22', '$f23', '$f24', '$f25', '$f26', '$f27', '$f28', '$f29', '$f30', '$f31']

TEMPLATE = {
    'REG32' : (1, 32, ['$t0'],
            ['$3', '$4', '$5', '$6', '$7', '$8', '$9', '$10', '$11', '$12', '$13', '$14', '$15', \
            '$16', '$17', '$18', '$19', '$20', '$21', '$22', '$23', '$24', '$25', '$26', '$27', '$28', '$29', '$30',
            '$v0', '$v1', '$a0', '$a1', '$a2', '$a3', '$t0', '$t1', '$t2', '$t3', '$t4', '$t5', '$t6', '$t7', \
            '$s0', '$s1', '$s2', '$s3', '$s4', '$s5', '$s6', '$s7', '$t8', '$t9']),
    'FP32' : (1, 32, ['$f0'],
            ['$f0', '$f2', '$f4', '$f6', '$f8', '$f10', '$f12', '$f14']),
    'MEMB' : (2, 0, ['($t0)'],
        ['($t0)', '($t1)', '($t2)', '($t3)', '($t4)', '($t5)', '($t6)', '($t7)',
        '($t8)', '($t9)', '($s0)', '($s1)', '($s2)', '($s3)', '($s4)', '($s5)',
        '($s6)', '($s7)']),
    'MEMBD' : (2, 0, ['1($t0)'],
        ['1($t0)', '1($t1)', '1($t2)', '1($t3)', '1($t4)', '1($t5)', '1($t6)',
        '1($t7)', '1($t8)', '1($t9)', '1($s0)', '1($s1)', '1($s2)', '1($s3)', '1($s4)',
        '1($s5)', '1($s6)', '1($s7)']),
    'MEMD' : (2, 0, ['(1)'],
            ['(1)','(2)','(3)','(4)','(5)','(6)','(7)','(8)']),
    'IMM' : (3, 0, ['1'],
            ['1','2','3','4','5','6','7','8'])
}
