OPCODE = ['add', 'addw', 'amoadd.d.aq', 'amoadd.d.aqrl', 'amoadd.d.rl', 'amoadd.d', 'amoadd.w.aq', 'amoadd.w.aqrl', 'amoadd.w.rl', 'amoadd.w', 'amoand.d.aq', 'amoand.d.aqrl', 'amoand.d.rl', 'amoand.d', 'amoand.w.aq', 'amoand.w.aqrl', 'amoand.w.rl', 'amoand.w', 'amomax.d.aq', 'amomax.d.aqrl', 'amomax.d.rl', 'amomax.d', 'amomax.w.aq', 'amomax.w.aqrl', 'amomax.w.rl', 'amomax.w', 'amomaxu.d.aq', 'amomaxu.d.aqrl', 'amomaxu.d.rl', 'amomaxu.d', 'amomaxu.w.aq', 'amomaxu.w.aqrl', 'amomaxu.w.rl', 'amomaxu.w', 'amomin.d.aq', 'amomin.d.aqrl', 'amomin.d.rl', 'amomin.d', 'amomin.w.aq', 'amomin.w.aqrl', 'amomin.w.rl', 'amomin.w', 'amominu.d.aq', 'amominu.d.aqrl', 'amominu.d.rl', 'amominu.d', 'amominu.w.aq', 'amominu.w.aqrl', 'amominu.w.rl', 'amominu.w', 'amoor.d.aq', 'amoor.d.aqrl', 'amoor.d.rl', 'amoor.d', 'amoor.w.aq', 'amoor.w.aqrl', 'amoor.w.rl', 'amoor.w', 'amoswap.d.aq', 'amoswap.d.aqrl', 'amoswap.d.rl', 'amoswap.d', 'amoswap.w.aq', 'amoswap.w.aqrl', 'amoswap.w.rl', 'amoswap.w', 'amoxor.d.aq', 'amoxor.d.aqrl', 'amoxor.d.rl', 'amoxor.d', 'amoxor.w.aq', 'amoxor.w.aqrl', 'amoxor.w.rl', 'amoxor.w', 'and', 'auipc', 'csrc', 'csrrc', 'csrrs', 'csrs', 'div', 'divu', 'divuw', 'divw', 'dret', 'ebreak', 'ecall', 'fabs.d', 'fabs.s', 'fadd.d', 'fadd.s', 'fclass.d', 'fclass.s', 'fcvt.d.l', 'fcvt.d.lu', 'fcvt.d.s', 'fcvt.d.w', 'fcvt.d.wu', 'fcvt.l.d', 'fcvt.l.s', 'fcvt.lu.d', 'fcvt.lu.s', 'fcvt.s.d', 'fcvt.s.l', 'fcvt.s.lu', 'fcvt.s.w', 'fcvt.s.wu', 'fcvt.w.d', 'fcvt.w.s', 'fcvt.wu.d', 'fcvt.wu.s', 'fdiv.d', 'fdiv.s', 'fence.i', 'fence', 'fence.tso', 'feq.d', 'feq.s', 'fld', 'fle.d', 'fle.s', 'flt.d', 'flt.s', 'flw', 'fmadd.d', 'fmadd.s', 'fmax.d', 'fmax.s', 'fmin.d', 'fmin.s', 'fmsub.d', 'fmsub.s', 'fmul.d', 'fmul.s', 'fmv.d', 'fmv.d.x', 'fmv.s', 'fmv.w.x', 'fmv.x.d', 'fmv.x.w', 'fneg.d', 'fneg.s', 'fnmadd.d', 'fnmadd.s', 'fnmsub.d', 'fnmsub.s', 'frcsr', 'frflags', 'frrm', 'fscsr', 'fsd', 'fsflags', 'fsflagsi', 'fsqrt.d', 'fsqrt.s', 'fsrm', 'fsrmi', 'fsub.d', 'fsub.s', 'fsw', 'hret', 'j', 'jal', 'jalr', 'jr', 'lb', 'lbu', 'ld', 'lh', 'lhu', 'li', 'lr.d.aq', 'lr.d.aqrl', 'lr.d.rl', 'lr.d', 'lr.w.aq', 'lr.w.aqrl', 'lr.w.rl', 'lr.w', 'lui', 'lw', 'lwu', 'mret', 'mul', 'mulh', 'mulhsu', 'mulhu', 'mulw', 'mv', 'neg', 'negw', 'nop', 'not', 'or', 'rdcycle', 'rdinstret', 'rdtime', 'rem', 'remu', 'remuw', 'remw', 'ret', 'sb', 'sc.d.aq', 'sc.d.aqrl', 'sc.d.rl', 'sc.d', 'sc.w.aq', 'sc.w.aqrl', 'sc.w.rl', 'sc.w', 'sd', 'seqz', 'sext.w', 'sfence.vm', 'sfence.vma', 'sgtz', 'sh', 'sll', 'sllw', 'slt', 'slti', 'sltu', 'sltz', 'snez', 'sra', 'sraw', 'sret', 'srl', 'srlw', 'sub', 'subw', 'sw', 'unimp', 'uret', 'wfi', 'xor', 'zext.b']
# OPCODE = ['add', 'add.uw', 'addi', 'addiw', 'addw', 'aes32dsi', 'aes32dsmi',
# 'aes32esi', 'aes32esmi', 'aes64ds', 'aes64dsm', 'aes64es', 'aes64esm',
# 'aes64im', 'aes64ks1i', 'aes64ks2', 'amoadd.d', 'amoadd.d.aq', 'amoadd.d.aqrl',
# 'amoadd.d.rl', 'amoadd.w', 'amoadd.w.aq', 'amoadd.w.aqrl', 'amoadd.w.rl',
# 'amoand.d', 'amoand.d.aq', 'amoand.d.aqrl', 'amoand.d.rl', 'amoand.w',
# 'amoand.w.aq', 'amoand.w.aqrl', 'amoand.w.rl', 'amomax.d', 'amomax.d.aq',
# 'amomax.d.aqrl', 'amomax.d.rl', 'amomax.w', 'amomax.w.aq', 'amomax.w.aqrl',
# 'amomax.w.rl', 'amomaxu.d', 'amomaxu.d.aq', 'amomaxu.d.aqrl', 'amomaxu.d.rl',
# 'amomaxu.w', 'amomaxu.w.aq', 'amomaxu.w.aqrl', 'amomaxu.w.rl', 'amomin.d',
# 'amomin.d.aq', 'amomin.d.aqrl', 'amomin.d.rl', 'amomin.w', 'amomin.w.aq',
# 'amomin.w.aqrl', 'amomin.w.rl', 'amominu.d', 'amominu.d.aq', 'amominu.d.aqrl',
# 'amominu.d.rl', 'amominu.w', 'amominu.w.aq', 'amominu.w.aqrl', 'amominu.w.rl',
# 'amoor.d', 'amoor.d.aq', 'amoor.d.aqrl', 'amoor.d.rl', 'amoor.w', 'amoor.w.aq',
# 'amoor.w.aqrl', 'amoor.w.rl', 'amoswap.d', 'amoswap.d.aq', 'amoswap.d.aqrl',
# 'amoswap.d.rl', 'amoswap.w', 'amoswap.w.aq', 'amoswap.w.aqrl', 'amoswap.w.rl',
# 'amoxor.d', 'amoxor.d.aq', 'amoxor.d.aqrl', 'amoxor.d.rl', 'amoxor.w',
# 'amoxor.w.aq', 'amoxor.w.aqrl', 'amoxor.w.rl', 'and', 'andi', 'andn', 'auipc',
# 'bclr', 'bclri', 'beq', 'beqz', 'bext', 'bexti', 'bge', 'bgeu', 'bgez', 'bgt',
# 'bgtu', 'bgtz', 'binv', 'binvi', 'ble', 'bleu', 'blez', 'blt', 'bltu', 'bltz',
# 'bne', 'bnez', 'brev8', 'bset', 'bseti', 'c.add', 'c.addi', 'c.addi16sp',
# 'c.addi4spn', 'c.addiw', 'c.addw', 'c.and', 'c.andi', 'c.beqz', 'c.bnez',
# 'c.ebreak', 'c.fld', 'c.fldsp', 'c.flw', 'c.flwsp', 'c.fsd', 'c.fsdsp',
# 'c.fsw', 'c.fswsp', 'c.j', 'c.jal', 'c.jalr', 'c.jr', 'c.ld', 'c.ldsp', 'c.li',
# 'c.lui', 'c.lw', 'c.lwsp', 'c.mv', 'c.nop', 'c.or', 'c.sd', 'c.sdsp', 'c.slli',
# 'c.slli64', 'c.srai', 'c.srai64', 'c.srli', 'c.srli64', 'c.sub', 'c.subw',
# 'c.sw', 'c.swsp', 'c.unimp', 'c.xor', 'call', 'cbo.clean', 'cbo.flush',
# 'cbo.inval', 'cbo.zero', 'clmul', 'clmulh', 'clmulr', 'clz', 'clzw', 'cpop',
# 'cpopw', 'csrc', 'csrci', 'csrr', 'csrrc', 'csrrci', 'csrrs', 'csrrsi',
# 'csrrw', 'csrrwi', 'csrs', 'csrsi', 'csrw', 'csrwi', 'ctz', 'ctzw',
# 'czero.eqz', 'czero.nez', 'div', 'divu', 'divuw', 'divw', 'dret', 'ebreak',
# 'ecall', 'fabs.d', 'fabs.h', 'fabs.q', 'fabs.s', 'fadd.d', 'fadd.h', 'fadd.q',
# 'fadd.s', 'fclass.d', 'fclass.h', 'fclass.q', 'fclass.s', 'fcvt.d.h',
# 'fcvt.d.l', 'fcvt.d.lu', 'fcvt.d.q', 'fcvt.d.s', 'fcvt.d.w', 'fcvt.d.wu',
# 'fcvt.h.d', 'fcvt.h.l', 'fcvt.h.lu', 'fcvt.h.q', 'fcvt.h.s', 'fcvt.h.w',
# 'fcvt.h.wu', 'fcvt.l.d', 'fcvt.l.h', 'fcvt.l.q', 'fcvt.l.s', 'fcvt.lu.d',
# 'fcvt.lu.h', 'fcvt.lu.q', 'fcvt.lu.s', 'fcvt.q.d', 'fcvt.q.h', 'fcvt.q.l',
# 'fcvt.q.lu', 'fcvt.q.s', 'fcvt.q.w', 'fcvt.q.wu', 'fcvt.s.d', 'fcvt.s.h',
# 'fcvt.s.l', 'fcvt.s.lu', 'fcvt.s.q', 'fcvt.s.w', 'fcvt.s.wu', 'fcvt.w.d',
# 'fcvt.w.h', 'fcvt.w.q', 'fcvt.w.s', 'fcvt.wu.d', 'fcvt.wu.h', 'fcvt.wu.q',
# 'fcvt.wu.s', 'fcvtmod.w.d', 'fdiv.d', 'fdiv.h', 'fdiv.q', 'fdiv.s', 'fence',
# 'fence.i', 'fence.tso', 'feq.d', 'feq.h', 'feq.q', 'feq.s', 'fge.d', 'fge.h',
# 'fge.q', 'fge.s', 'fgt.d', 'fgt.h', 'fgt.q', 'fgt.s', 'fld', 'fle.d', 'fle.h',
# 'fle.q', 'fle.s', 'fleq.d', 'fleq.h', 'fleq.q', 'fleq.s', 'flh', 'fli.d',
# 'fli.h', 'fli.q', 'fli.s', 'flq', 'flt.d', 'flt.h', 'flt.q', 'flt.s', 'fltq.d',
# 'fltq.h', 'fltq.q', 'fltq.s', 'flw', 'fmadd.d', 'fmadd.h', 'fmadd.q',
# 'fmadd.s', 'fmax.d', 'fmax.h', 'fmax.q', 'fmax.s', 'fmaxm.d', 'fmaxm.h',
# 'fmaxm.q', 'fmaxm.s', 'fmin.d', 'fmin.h', 'fmin.q', 'fmin.s', 'fminm.d',
# 'fminm.h', 'fminm.q', 'fminm.s', 'fmsub.d', 'fmsub.h', 'fmsub.q', 'fmsub.s',
# 'fmul.d', 'fmul.h', 'fmul.q', 'fmul.s', 'fmv.d', 'fmv.d.x', 'fmv.h', 'fmv.h.x',
# 'fmv.q', 'fmv.s', 'fmv.s.x', 'fmv.w.x', 'fmv.x.d', 'fmv.x.h', 'fmv.x.s',
# 'fmv.x.w', 'fmvh.x.d', 'fmvh.x.q', 'fmvp.d.x', 'fmvp.q.x', 'fneg.d', 'fneg.h',
# 'fneg.q', 'fneg.s', 'fnmadd.d', 'fnmadd.h', 'fnmadd.q', 'fnmadd.s', 'fnmsub.d',
# 'fnmsub.h', 'fnmsub.q', 'fnmsub.s', 'frcsr', 'frflags', 'fround.d', 'fround.h',
# 'fround.q', 'fround.s', 'froundnx.d', 'froundnx.h', 'froundnx.q', 'froundnx.s',
# 'frrm', 'frsr', 'fscsr', 'fsd', 'fsflags', 'fsflagsi', 'fsgnj.d', 'fsgnj.h',
# 'fsgnj.q', 'fsgnj.s', 'fsgnjn.d', 'fsgnjn.h', 'fsgnjn.q', 'fsgnjn.s',
# 'fsgnjx.d', 'fsgnjx.h', 'fsgnjx.q', 'fsgnjx.s', 'fsh', 'fsq', 'fsqrt.d',
# 'fsqrt.h', 'fsqrt.q', 'fsqrt.s', 'fsrm', 'fsrmi', 'fssr', 'fsub.d', 'fsub.h',
# 'fsub.q', 'fsub.s', 'fsw', 'hfence.gvma', 'hfence.vvma', 'hinval.gvma',
# 'hinval.vvma', 'hlv.b', 'hlv.bu', 'hlv.d', 'hlv.h', 'hlv.hu', 'hlv.w',
# 'hlv.wu', 'hlvx.hu', 'hlvx.wu', 'hret', 'hsv.b', 'hsv.d', 'hsv.h', 'hsv.w',
# 'j', 'jal', 'jalr', 'jr', 'jump', 'la', 'la.tls.gd', 'la.tls.ie', 'lb', 'lbu',
# 'ld', 'lga', 'lh', 'lhu', 'li', 'lla', 'lr.d', 'lr.d.aq', 'lr.d.aqrl',
# 'lr.d.rl', 'lr.w', 'lr.w.aq', 'lr.w.aqrl', 'lr.w.rl', 'lui', 'lw', 'lwu',
# 'max', 'maxu', 'min', 'minu', 'move', 'mret', 'mul', 'mulh', 'mulhsu', 'mulhu',
# 'mulw', 'mv', 'neg', 'negw', 'nop', 'not', 'or', 'orc.b', 'ori', 'orn', 'pack',
# 'packh', 'packw', 'pause', 'prefetch.i', 'prefetch.r', 'prefetch.w', 'rdcycle',
# 'rdcycleh', 'rdinstret', 'rdinstreth', 'rdtime', 'rdtimeh', 'rem', 'remu',
# 'remuw', 'remw', 'ret', 'rev8', 'rol', 'rolw', 'ror', 'rori', 'roriw', 'rorw',
# 'sb', 'sbreak', 'sc.d', 'sc.d.aq', 'sc.d.aqrl', 'sc.d.rl', 'sc.w', 'sc.w.aq',
# 'sc.w.aqrl', 'sc.w.rl', 'scall', 'sd', 'seqz', 'sext.b', 'sext.h', 'sext.w',
# 'sfence.inval.ir', 'sfence.vm', 'sfence.vma', 'sfence.w.inval', 'sgt', 'sgtu',
# 'sgtz', 'sh', 'sh1add', 'sh1add.uw', 'sh2add', 'sh2add.uw', 'sh3add',
# 'sh3add.uw', 'sha256sig0', 'sha256sig1', 'sha256sum0', 'sha256sum1',
# 'sha512sig0', 'sha512sig0h', 'sha512sig0l', 'sha512sig1', 'sha512sig1h',
# 'sha512sig1l', 'sha512sum0', 'sha512sum0r', 'sha512sum1', 'sha512sum1r',
# 'sinval.vma', 'sll', 'slli', 'slli.uw', 'slliw', 'sllw', 'slt', 'slti',
# 'sltiu', 'sltu', 'sltz', 'sm3p0', 'sm3p1', 'sm4ed', 'sm4ks', 'snez', 'sra',
# 'srai', 'sraiw', 'sraw', 'sret', 'srl', 'srli', 'srliw', 'srlw', 'sub', 'subw',
# 'sw', 'tail', 'th.addsl', 'th.dcache.call', 'th.dcache.ciall',
# 'th.dcache.cipa', 'th.dcache.cisw', 'th.dcache.civa', 'th.dcache.cpa',
# 'th.dcache.cpal1', 'th.dcache.csw', 'th.dcache.cva', 'th.dcache.cval1',
# 'th.dcache.iall', 'th.dcache.ipa', 'th.dcache.isw', 'th.dcache.iva', 'th.ext',
# 'th.extu', 'th.ff0', 'th.ff1', 'th.flrd', 'th.flrw', 'th.flurd', 'th.flurw',
# 'th.fmv.hw.x', 'th.fmv.x.hw', 'th.fsrd', 'th.fsrw', 'th.fsurd', 'th.fsurw',
# 'th.icache.iall', 'th.icache.ialls', 'th.icache.ipa', 'th.icache.iva',
# 'th.ipop', 'th.ipush', 'th.l2cache.call', 'th.l2cache.ciall',
# 'th.l2cache.iall', 'th.lbia', 'th.lbib', 'th.lbuia', 'th.lbuib', 'th.ldd',
# 'th.ldia', 'th.ldib', 'th.lhia', 'th.lhib', 'th.lhuia', 'th.lhuib', 'th.lrb',
# 'th.lrbu', 'th.lrd', 'th.lrh', 'th.lrhu', 'th.lrw', 'th.lrwu', 'th.lurb',
# 'th.lurbu', 'th.lurd', 'th.lurh', 'th.lurhu', 'th.lurw', 'th.lurwu', 'th.lwd',
# 'th.lwia', 'th.lwib', 'th.lwud', 'th.lwuia', 'th.lwuib', 'th.mula', 'th.mulah',
# 'th.mulaw', 'th.muls', 'th.mulsh', 'th.mulsw', 'th.mveqz', 'th.mvnez',
# 'th.rev', 'th.revw', 'th.sbia', 'th.sbib', 'th.sdd', 'th.sdia', 'th.sdib',
# 'th.sfence.vmas', 'th.shia', 'th.shib', 'th.srb', 'th.srd', 'th.srh',
# 'th.srri', 'th.srriw', 'th.srw', 'th.surb', 'th.surd', 'th.surh', 'th.surw',
# 'th.swd', 'th.swia', 'th.swib', 'th.sync', 'th.sync.i', 'th.sync.is',
# 'th.sync.s', 'th.tst', 'th.tstnbz', 'unimp', 'unzip', 'uret', 'vaadd.vv',
# 'vaadd.vx', 'vaaddu.vv', 'vaaddu.vx', 'vadc.vim', 'vadc.vvm', 'vadc.vxm',
# 'vadd.vi', 'vadd.vv', 'vadd.vx', 'vaesdf.vs', 'vaesdf.vv', 'vaesdm.vs',
# 'vaesdm.vv', 'vaesef.vs', 'vaesef.vv', 'vaesem.vs', 'vaesem.vv', 'vaeskf1.vi',
# 'vaeskf2.vi', 'vaesz.vs', 'vand.vi', 'vand.vv', 'vand.vx', 'vandn.vv',
# 'vandn.vx', 'vasub.vv', 'vasub.vx', 'vasubu.vv', 'vasubu.vx', 'vbrev.v',
# 'vbrev8.v', 'vclmul.vv', 'vclmul.vx', 'vclmulh.vv', 'vclmulh.vx', 'vclz.v',
# 'vcompress.vm', 'vcpop.m', 'vcpop.v', 'vctz.v', 'vdiv.vv', 'vdiv.vx',
# 'vdivu.vv', 'vdivu.vx', 'vfabs.v', 'vfadd.vf', 'vfadd.vv', 'vfclass.v',
# 'vfcvt.f.x.v', 'vfcvt.f.xu.v', 'vfcvt.rtz.x.f.v', 'vfcvt.rtz.xu.f.v',
# 'vfcvt.x.f.v', 'vfcvt.xu.f.v', 'vfdiv.vf', 'vfdiv.vv', 'vfirst.m', 'vfmacc.vf',
# 'vfmacc.vv', 'vfmadd.vf', 'vfmadd.vv', 'vfmax.vf', 'vfmax.vv', 'vfmerge.vfm',
# 'vfmin.vf', 'vfmin.vv', 'vfmsac.vf', 'vfmsac.vv', 'vfmsub.vf', 'vfmsub.vv',
# 'vfmul.vf', 'vfmul.vv', 'vfmv.f.s', 'vfmv.s.f', 'vfmv.v.f', 'vfncvt.f.f.w',
# 'vfncvt.f.x.w', 'vfncvt.f.xu.w', 'vfncvt.rod.f.f.w', 'vfncvt.rtz.x.f.w',
# 'vfncvt.rtz.xu.f.w', 'vfncvt.x.f.w', 'vfncvt.xu.f.w', 'vfneg.v', 'vfnmacc.vf',
# 'vfnmacc.vv', 'vfnmadd.vf', 'vfnmadd.vv', 'vfnmsac.vf', 'vfnmsac.vv',
# 'vfnmsub.vf', 'vfnmsub.vv', 'vfrdiv.vf', 'vfrec7.v', 'vfrece7.v',
# 'vfredmax.vs', 'vfredmin.vs', 'vfredosum.vs', 'vfredsum.vs', 'vfredusum.vs',
# 'vfrsqrt7.v', 'vfrsqrte7.v', 'vfrsub.vf', 'vfsgnj.vf', 'vfsgnj.vv',
# 'vfsgnjn.vf', 'vfsgnjn.vv', 'vfsgnjx.vf', 'vfsgnjx.vv', 'vfslide1down.vf',
# 'vfslide1up.vf', 'vfsqrt.v', 'vfsub.vf', 'vfsub.vv', 'vfwadd.vf', 'vfwadd.vv',
# 'vfwadd.wf', 'vfwadd.wv', 'vfwcvt.f.f.v', 'vfwcvt.f.x.v', 'vfwcvt.f.xu.v',
# 'vfwcvt.rtz.x.f.v', 'vfwcvt.rtz.xu.f.v', 'vfwcvt.x.f.v', 'vfwcvt.xu.f.v',
# 'vfwmacc.vf', 'vfwmacc.vv', 'vfwmsac.vf', 'vfwmsac.vv', 'vfwmul.vf',
# 'vfwmul.vv', 'vfwnmacc.vf', 'vfwnmacc.vv', 'vfwnmsac.vf', 'vfwnmsac.vv',
# 'vfwredosum.vs', 'vfwredsum.vs', 'vfwredusum.vs', 'vfwsub.vf', 'vfwsub.vv',
# 'vfwsub.wf', 'vfwsub.wv', 'vghsh.vv', 'vgmul.vv', 'vid.v', 'viota.m', 'vl1r.v',
# 'vl1re16.v', 'vl1re32.v', 'vl1re64.v', 'vl1re8.v', 'vl2r.v', 'vl2re16.v',
# 'vl2re32.v', 'vl2re64.v', 'vl2re8.v', 'vl4r.v', 'vl4re16.v', 'vl4re32.v',
# 'vl4re64.v', 'vl4re8.v', 'vl8r.v', 'vl8re16.v', 'vl8re32.v', 'vl8re64.v',
# 'vl8re8.v', 'vle1.v', 'vle16.v', 'vle16ff.v', 'vle32.v', 'vle32ff.v',
# 'vle64.v', 'vle64ff.v', 'vle8.v', 'vle8ff.v', 'vlm.v', 'vloxei16.v',
# 'vloxei32.v', 'vloxei64.v', 'vloxei8.v', 'vloxseg2ei16.v', 'vloxseg2ei32.v',
# 'vloxseg2ei64.v', 'vloxseg2ei8.v', 'vloxseg3ei16.v', 'vloxseg3ei32.v',
# 'vloxseg3ei64.v', 'vloxseg3ei8.v', 'vloxseg4ei16.v', 'vloxseg4ei32.v',
# 'vloxseg4ei64.v', 'vloxseg4ei8.v', 'vloxseg5ei16.v', 'vloxseg5ei32.v',
# 'vloxseg5ei64.v', 'vloxseg5ei8.v', 'vloxseg6ei16.v', 'vloxseg6ei32.v',
# 'vloxseg6ei64.v', 'vloxseg6ei8.v', 'vloxseg7ei16.v', 'vloxseg7ei32.v',
# 'vloxseg7ei64.v', 'vloxseg7ei8.v', 'vloxseg8ei16.v', 'vloxseg8ei32.v',
# 'vloxseg8ei64.v', 'vloxseg8ei8.v', 'vlse16.v', 'vlse32.v', 'vlse64.v',
# 'vlse8.v', 'vlseg2e16.v', 'vlseg2e16ff.v', 'vlseg2e32.v', 'vlseg2e32ff.v',
# 'vlseg2e64.v', 'vlseg2e64ff.v', 'vlseg2e8.v', 'vlseg2e8ff.v', 'vlseg3e16.v',
# 'vlseg3e16ff.v', 'vlseg3e32.v', 'vlseg3e32ff.v', 'vlseg3e64.v',
# 'vlseg3e64ff.v', 'vlseg3e8.v', 'vlseg3e8ff.v', 'vlseg4e16.v', 'vlseg4e16ff.v',
# 'vlseg4e32.v', 'vlseg4e32ff.v', 'vlseg4e64.v', 'vlseg4e64ff.v', 'vlseg4e8.v',
# 'vlseg4e8ff.v', 'vlseg5e16.v', 'vlseg5e16ff.v', 'vlseg5e32.v', 'vlseg5e32ff.v',
# 'vlseg5e64.v', 'vlseg5e64ff.v', 'vlseg5e8.v', 'vlseg5e8ff.v', 'vlseg6e16.v',
# 'vlseg6e16ff.v', 'vlseg6e32.v', 'vlseg6e32ff.v', 'vlseg6e64.v',
# 'vlseg6e64ff.v', 'vlseg6e8.v', 'vlseg6e8ff.v', 'vlseg7e16.v', 'vlseg7e16ff.v',
# 'vlseg7e32.v', 'vlseg7e32ff.v', 'vlseg7e64.v', 'vlseg7e64ff.v', 'vlseg7e8.v',
# 'vlseg7e8ff.v', 'vlseg8e16.v', 'vlseg8e16ff.v', 'vlseg8e32.v', 'vlseg8e32ff.v',
# 'vlseg8e64.v', 'vlseg8e64ff.v', 'vlseg8e8.v', 'vlseg8e8ff.v', 'vlsseg2e16.v',
# 'vlsseg2e32.v', 'vlsseg2e64.v', 'vlsseg2e8.v', 'vlsseg3e16.v', 'vlsseg3e32.v',
# 'vlsseg3e64.v', 'vlsseg3e8.v', 'vlsseg4e16.v', 'vlsseg4e32.v', 'vlsseg4e64.v',
# 'vlsseg4e8.v', 'vlsseg5e16.v', 'vlsseg5e32.v', 'vlsseg5e64.v', 'vlsseg5e8.v',
# 'vlsseg6e16.v', 'vlsseg6e32.v', 'vlsseg6e64.v', 'vlsseg6e8.v', 'vlsseg7e16.v',
# 'vlsseg7e32.v', 'vlsseg7e64.v', 'vlsseg7e8.v', 'vlsseg8e16.v', 'vlsseg8e32.v',
# 'vlsseg8e64.v', 'vlsseg8e8.v', 'vluxei16.v', 'vluxei32.v', 'vluxei64.v',
# 'vluxei8.v', 'vluxseg2ei16.v', 'vluxseg2ei32.v', 'vluxseg2ei64.v',
# 'vluxseg2ei8.v', 'vluxseg3ei16.v', 'vluxseg3ei32.v', 'vluxseg3ei64.v',
# 'vluxseg3ei8.v', 'vluxseg4ei16.v', 'vluxseg4ei32.v', 'vluxseg4ei64.v',
# 'vluxseg4ei8.v', 'vluxseg5ei16.v', 'vluxseg5ei32.v', 'vluxseg5ei64.v',
# 'vluxseg5ei8.v', 'vluxseg6ei16.v', 'vluxseg6ei32.v', 'vluxseg6ei64.v',
# 'vluxseg6ei8.v', 'vluxseg7ei16.v', 'vluxseg7ei32.v', 'vluxseg7ei64.v',
# 'vluxseg7ei8.v', 'vluxseg8ei16.v', 'vluxseg8ei32.v', 'vluxseg8ei64.v',
# 'vluxseg8ei8.v', 'vmacc.vv', 'vmacc.vx', 'vmadc.vi', 'vmadc.vim', 'vmadc.vv',
# 'vmadc.vvm', 'vmadc.vx', 'vmadc.vxm', 'vmadd.vv', 'vmadd.vx', 'vmand.mm',
# 'vmandn.mm', 'vmandnot.mm', 'vmax.vv', 'vmax.vx', 'vmaxu.vv', 'vmaxu.vx',
# 'vmclr.m', 'vmcpy.m', 'vmerge.vim', 'vmerge.vvm', 'vmerge.vxm', 'vmfeq.vf',
# 'vmfeq.vv', 'vmfge.vf', 'vmfge.vv', 'vmfgt.vf', 'vmfgt.vv', 'vmfle.vf',
# 'vmfle.vv', 'vmflt.vf', 'vmflt.vv', 'vmfne.vf', 'vmfne.vv', 'vmin.vv',
# 'vmin.vx', 'vminu.vv', 'vminu.vx', 'vmmv.m', 'vmnand.mm', 'vmnor.mm',
# 'vmnot.m', 'vmor.mm', 'vmorn.mm', 'vmornot.mm', 'vmsbc.vv', 'vmsbc.vvm',
# 'vmsbc.vx', 'vmsbc.vxm', 'vmsbf.m', 'vmseq.vi', 'vmseq.vv', 'vmseq.vx',
# 'vmset.m', 'vmsge.vi', 'vmsge.vv', 'vmsge.vx', 'vmsgeu.vi', 'vmsgeu.vv',
# 'vmsgeu.vx', 'vmsgt.vi', 'vmsgt.vv', 'vmsgt.vx', 'vmsgtu.vi', 'vmsgtu.vv',
# 'vmsgtu.vx', 'vmsif.m', 'vmsle.vi', 'vmsle.vv', 'vmsle.vx', 'vmsleu.vi',
# 'vmsleu.vv', 'vmsleu.vx', 'vmslt.vi', 'vmslt.vv', 'vmslt.vx', 'vmsltu.vi',
# 'vmsltu.vv', 'vmsltu.vx', 'vmsne.vi', 'vmsne.vv', 'vmsne.vx', 'vmsof.m',
# 'vmul.vv', 'vmul.vx', 'vmulh.vv', 'vmulh.vx', 'vmulhsu.vv', 'vmulhsu.vx',
# 'vmulhu.vv', 'vmulhu.vx', 'vmv.s.x', 'vmv.v.i', 'vmv.v.v', 'vmv.v.x',
# 'vmv.x.s', 'vmv1r.v', 'vmv2r.v', 'vmv4r.v', 'vmv8r.v', 'vmxnor.mm', 'vmxor.mm',
# 'vnclip.wi', 'vnclip.wv', 'vnclip.wx', 'vnclipu.wi', 'vnclipu.wv',
# 'vnclipu.wx', 'vncvt.x.x.w', 'vneg.v', 'vnmsac.vv', 'vnmsac.vx', 'vnmsub.vv',
# 'vnmsub.vx', 'vnot.v', 'vnsra.wi', 'vnsra.wv', 'vnsra.wx', 'vnsrl.wi',
# 'vnsrl.wv', 'vnsrl.wx', 'vor.vi', 'vor.vv', 'vor.vx', 'vpopc.m', 'vredand.vs',
# 'vredmax.vs', 'vredmaxu.vs', 'vredmin.vs', 'vredminu.vs', 'vredor.vs',
# 'vredsum.vs', 'vredxor.vs', 'vrem.vv', 'vrem.vx', 'vremu.vv', 'vremu.vx',
# 'vrev8.v', 'vrgather.vi', 'vrgather.vv', 'vrgather.vx', 'vrgatherei16.vv',
# 'vrol.vv', 'vrol.vx', 'vror.vi', 'vror.vv', 'vror.vx', 'vrsub.vi', 'vrsub.vx',
# 'vs1r.v', 'vs2r.v', 'vs4r.v', 'vs8r.v', 'vsadd.vi', 'vsadd.vv', 'vsadd.vx',
# 'vsaddu.vi', 'vsaddu.vv', 'vsaddu.vx', 'vsbc.vvm', 'vsbc.vxm', 'vse1.v',
# 'vse16.v', 'vse32.v', 'vse64.v', 'vse8.v', 'vsetivli', 'vsetvl', 'vsetvli',
# 'vsext.vf2', 'vsext.vf4', 'vsext.vf8', 'vsha2ch.vv', 'vsha2cl.vv',
# 'vsha2ms.vv', 'vslide1down.vx', 'vslide1up.vx', 'vslidedown.vi',
# 'vslidedown.vx', 'vslideup.vi', 'vslideup.vx', 'vsll.vi', 'vsll.vv', 'vsll.vx',
# 'vsm.v', 'vsm3c.vi', 'vsm3me.vv', 'vsm4k.vi', 'vsm4r.vs', 'vsm4r.vv',
# 'vsmul.vv', 'vsmul.vx', 'vsoxei16.v', 'vsoxei32.v', 'vsoxei64.v', 'vsoxei8.v',
# 'vsoxseg2ei16.v', 'vsoxseg2ei32.v', 'vsoxseg2ei64.v', 'vsoxseg2ei8.v',
# 'vsoxseg3ei16.v', 'vsoxseg3ei32.v', 'vsoxseg3ei64.v', 'vsoxseg3ei8.v',
# 'vsoxseg4ei16.v', 'vsoxseg4ei32.v', 'vsoxseg4ei64.v', 'vsoxseg4ei8.v',
# 'vsoxseg5ei16.v', 'vsoxseg5ei32.v', 'vsoxseg5ei64.v', 'vsoxseg5ei8.v',
# 'vsoxseg6ei16.v', 'vsoxseg6ei32.v', 'vsoxseg6ei64.v', 'vsoxseg6ei8.v',
# 'vsoxseg7ei16.v', 'vsoxseg7ei32.v', 'vsoxseg7ei64.v', 'vsoxseg7ei8.v',
# 'vsoxseg8ei16.v', 'vsoxseg8ei32.v', 'vsoxseg8ei64.v', 'vsoxseg8ei8.v',
# 'vsra.vi', 'vsra.vv', 'vsra.vx', 'vsrl.vi', 'vsrl.vv', 'vsrl.vx', 'vsse16.v',
# 'vsse32.v', 'vsse64.v', 'vsse8.v', 'vsseg2e16.v', 'vsseg2e32.v', 'vsseg2e64.v',
# 'vsseg2e8.v', 'vsseg3e16.v', 'vsseg3e32.v', 'vsseg3e64.v', 'vsseg3e8.v',
# 'vsseg4e16.v', 'vsseg4e32.v', 'vsseg4e64.v', 'vsseg4e8.v', 'vsseg5e16.v',
# 'vsseg5e32.v', 'vsseg5e64.v', 'vsseg5e8.v', 'vsseg6e16.v', 'vsseg6e32.v',
# 'vsseg6e64.v', 'vsseg6e8.v', 'vsseg7e16.v', 'vsseg7e32.v', 'vsseg7e64.v',
# 'vsseg7e8.v', 'vsseg8e16.v', 'vsseg8e32.v', 'vsseg8e64.v', 'vsseg8e8.v',
# 'vssra.vi', 'vssra.vv', 'vssra.vx', 'vssrl.vi', 'vssrl.vv', 'vssrl.vx',
# 'vssseg2e16.v', 'vssseg2e32.v', 'vssseg2e64.v', 'vssseg2e8.v', 'vssseg3e16.v',
# 'vssseg3e32.v', 'vssseg3e64.v', 'vssseg3e8.v', 'vssseg4e16.v', 'vssseg4e32.v',
# 'vssseg4e64.v', 'vssseg4e8.v', 'vssseg5e16.v', 'vssseg5e32.v', 'vssseg5e64.v',
# 'vssseg5e8.v', 'vssseg6e16.v', 'vssseg6e32.v', 'vssseg6e64.v', 'vssseg6e8.v',
# 'vssseg7e16.v', 'vssseg7e32.v', 'vssseg7e64.v', 'vssseg7e8.v', 'vssseg8e16.v',
# 'vssseg8e32.v', 'vssseg8e64.v', 'vssseg8e8.v', 'vssub.vv', 'vssub.vx',
# 'vssubu.vv', 'vssubu.vx', 'vsub.vv', 'vsub.vx', 'vsuxei16.v', 'vsuxei32.v',
# 'vsuxei64.v', 'vsuxei8.v', 'vsuxseg2ei16.v', 'vsuxseg2ei32.v',
# 'vsuxseg2ei64.v', 'vsuxseg2ei8.v', 'vsuxseg3ei16.v', 'vsuxseg3ei32.v',
# 'vsuxseg3ei64.v', 'vsuxseg3ei8.v', 'vsuxseg4ei16.v', 'vsuxseg4ei32.v',
# 'vsuxseg4ei64.v', 'vsuxseg4ei8.v', 'vsuxseg5ei16.v', 'vsuxseg5ei32.v',
# 'vsuxseg5ei64.v', 'vsuxseg5ei8.v', 'vsuxseg6ei16.v', 'vsuxseg6ei32.v',
# 'vsuxseg6ei64.v', 'vsuxseg6ei8.v', 'vsuxseg7ei16.v', 'vsuxseg7ei32.v',
# 'vsuxseg7ei64.v', 'vsuxseg7ei8.v', 'vsuxseg8ei16.v', 'vsuxseg8ei32.v',
# 'vsuxseg8ei64.v', 'vsuxseg8ei8.v', 'vt.maskc', 'vt.maskcn', 'vwadd.vv',
# 'vwadd.vx', 'vwadd.wv', 'vwadd.wx', 'vwaddu.vv', 'vwaddu.vx', 'vwaddu.wv',
# 'vwaddu.wx', 'vwcvt.x.x.v', 'vwcvtu.x.x.v', 'vwmacc.vv', 'vwmacc.vx',
# 'vwmaccsu.vv', 'vwmaccsu.vx', 'vwmaccu.vv', 'vwmaccu.vx', 'vwmaccus.vx',
# 'vwmul.vv', 'vwmul.vx', 'vwmulsu.vv', 'vwmulsu.vx', 'vwmulu.vv', 'vwmulu.vx',
# 'vwredsum.vs', 'vwredsumu.vs', 'vwsll.vi', 'vwsll.vv', 'vwsll.vx', 'vwsub.vv',
# 'vwsub.vx', 'vwsub.wv', 'vwsub.wx', 'vwsubu.vv', 'vwsubu.vx', 'vwsubu.wv',
# 'vwsubu.wx', 'vxor.vi', 'vxor.vv', 'vxor.vx', 'vzext.vf2', 'vzext.vf4',
# 'vzext.vf8', 'wfi', 'wrs.nto', 'wrs.sto', 'xnor', 'xor', 'xori', 'xperm4',
# 'xperm8', 'zext.b', 'zext.h', 'zext.w', 'zip']

REGISTERS= [   "x0",   "x1",   "x2",   "x3",   "x4",   "x5",   "x6",   "x7",
  "x8",   "x9",   "x10",  "x11",  "x12",  "x13",  "x14",  "x15",
  "x16",  "x17",  "x18",  "x19",  "x20",  "x21",  "x22",  "x23",
  "x24",  "x25",  "x26",  "x27",  "x28",  "x29",  "x30",  "x31",
  "zero", "ra",   "sp",   "gp",   "tp",   "t0",   "t1",   "t2",
  "s0",   "s1",   "a0",   "a1",   "a2",   "a3",   "a4",   "a5",
  "a6",   "a7",   "s2",   "s3",   "s4",   "s5",   "s6",   "s7",
  "s8",   "s9",   "s10",  "s11",  "t3",   "t4",   "t5",   "t6",
  "f0",   "f1",   "f2",   "f3",   "f4",   "f5",   "f6",   "f7",
  "f8",   "f9",   "f10",  "f11",  "f12",  "f13",  "f14",  "f15",
  "f16",  "f17",  "f18",  "f19",  "f20",  "f21",  "f22",  "f23",
  "f24",  "f25",  "f26",  "f27",  "f28",  "f29",  "f30",  "f31",
  "ft0",  "ft1",  "ft2",  "ft3",  "ft4",  "ft5",  "ft6",  "ft7",
  "fs0",  "fs1",  "fa0",  "fa1",  "fa2",  "fa3",  "fa4",  "fa5",
  "fa6",  "fa7",  "fs2",  "fs3",  "fs4",  "fs5",  "fs6",  "fs7",
  "fs8",  "fs9",  "fs10", "fs11", "ft8",  "ft9",  "ft10", "ft11",
  "v0",   "v1",   "v2",   "v3",   "v4",   "v5",   "v6",   "v7",
  "v8",   "v9",   "v10",  "v11",  "v12",  "v13",  "v14",  "v15",
  "v16",  "v17",  "v18",  "v19",  "v20",  "v21",  "v22",  "v23",
  "v24",  "v25",  "v26",  "v27",  "v28",  "v29",  "v30",  "v31" ]

# ref https://marz.utk.edu/my-courses/cosc230/book/example-risc-v-assembly-programs/
# https://en.wikichip.org/wiki/risc-v/registers
TEMPLATE = {
    'REG64' : (1, 64, ['a0'], # same as t0, x0 is zero register
            [  "zero", "ra",   "sp",   "gp",   "tp",   "t0",   "t1",   "t2",
              "s0",   "s1",   "a0",   "a1",   "a2",   "a3",   "a4",   "a5",
              "a6",   "a7",   "s2",   "s3",   "s4",   "s5",   "s6",   "s7",
              "s8",   "s9",   "s10",  "s11",  "t3",   "t4",   "t5",   "t6"]
            ),
    'FP64' : (1, 64, ['ft0'],
			['ft0', 'ft1', 'ft2', 'ft3', 'ft4', 'ft5', 'ft6', 'ft7', 'ft8', 'ft9']),
    'MEMB' : (2, 0, ['(a0)'],
                ['(a0)',
          "(s0)",   "(s1)",   "(a0)",   "(a1)",   "(a2)",   "(a3)",   "(a4)",   "(a5)",
          "(a6)",   "(a7)",   "(s2)",   "(s3)",   "(s4)",   "(s5)",   "(s6)",   "(s7)",
          "(s8)",   "(s9)",   "(s10)",  "(s11)",  "(t3)",   "(t4)",   "(t5)",   "(t6)"]),
    'MEMBD' : (2, 0, ['1(a0)'],
                ['1(a0)',
          "1(s0)",   "1(s1)",   "1(a0)",   "1(a1)",   "1(a2)",   "1(a3)",   "1(a4)",   "1(a5)",
          "1(a6)",   "1(a7)",   "1(s2)",   "1(s3)",   "1(s4)",   "1(s5)",   "1(s6)",   "1(s7)",
          "1(s8)",   "1(s9)",   "1(s10)",  "1(s11)",  "1(t3)",   "1(t4)",   "1(t5)",   "1(t6)"]),
    'MEMD' : (2, 0, ['(1)'],
                ['(1)', '(2)', '(3)', '(4)', '(5)', '(6)', '(7)', '(8)']),
    'IMM' : (3, 0, ['1'],
                ['1', '2', '3', '4', '5', '6', '7', '8'])
}
